// Extra words: Landen (125) + Sport (125)

export const extraWords2 = [

  // ─── LANDEN +125 ────────────────────────────────────────────
  { categoryId: 'cat-countries', word: 'Zuid-Korea',         hintEasy: 'K-pop',         hintMedium: 'Seoul',          hintHard: 'Samsung' },
  { categoryId: 'cat-countries', word: 'Noord-Korea',        hintEasy: 'Verboden',      hintMedium: 'Raket',          hintHard: 'Muur' },
  { categoryId: 'cat-countries', word: 'Taiwan',             hintEasy: 'Chip',          hintMedium: 'Eiland',         hintHard: 'Onafhankelijk' },
  { categoryId: 'cat-countries', word: 'Singapore',          hintEasy: 'Schoon',        hintMedium: 'Rijkdom',        hintHard: 'Kauwgom' },
  { categoryId: 'cat-countries', word: 'Maleisië',           hintEasy: 'Palmboom',      hintMedium: 'Moslim',         hintHard: 'Tweelingen' },
  { categoryId: 'cat-countries', word: 'Filipijnen',         hintEasy: 'Eilanden',      hintMedium: 'Oceaan',         hintHard: 'Tyfoon' },
  { categoryId: 'cat-countries', word: 'Cambodja',           hintEasy: 'Tempel',        hintMedium: 'Jungle',         hintHard: 'Angkor' },
  { categoryId: 'cat-countries', word: 'Myanmar',            hintEasy: 'Tempel',        hintMedium: 'Junta',          hintHard: 'Birma' },
  { categoryId: 'cat-countries', word: 'Sri Lanka',          hintEasy: 'Thee',          hintMedium: 'Eiland',         hintHard: 'Traan' },
  { categoryId: 'cat-countries', word: 'Nepal',              hintEasy: 'Bergen',        hintMedium: 'Everest',        hintHard: 'Sherpas' },
  { categoryId: 'cat-countries', word: 'Bangladesh',         hintEasy: 'Rivier',        hintMedium: 'Kleding',        hintHard: 'Delta' },
  { categoryId: 'cat-countries', word: 'Mongolië',           hintEasy: 'Woestijn',      hintMedium: 'Yurt',           hintHard: 'Genghis' },
  { categoryId: 'cat-countries', word: 'Oekraïne',           hintEasy: 'Zonnebloem',    hintMedium: 'Graan',          hintHard: 'Blauw-geel' },
  { categoryId: 'cat-countries', word: 'Tsjechië',           hintEasy: 'Bier',          hintMedium: 'Praag',          hintHard: 'Kristal' },
  { categoryId: 'cat-countries', word: 'Roemenië',           hintEasy: 'Karpaten',      hintMedium: 'Vampier',        hintHard: 'Casteel' },
  { categoryId: 'cat-countries', word: 'Bulgarije',          hintEasy: 'Yoghurt',       hintMedium: 'Zwarte Zee',     hintHard: 'Rozengaard' },
  { categoryId: 'cat-countries', word: 'Servië',             hintEasy: 'Balkan',        hintMedium: 'Tennis',         hintHard: 'Dobro' },
  { categoryId: 'cat-countries', word: 'Albanië',            hintEasy: 'Adelaar',       hintMedium: 'Balkan',         hintHard: 'Bunker' },
  { categoryId: 'cat-countries', word: 'Slovenië',           hintEasy: 'Bergen',        hintMedium: 'Alpen',          hintHard: 'Groen' },
  { categoryId: 'cat-countries', word: 'Bosnië',             hintEasy: 'Balkan',        hintMedium: 'Vrede',          hintHard: 'Brug' },
  { categoryId: 'cat-countries', word: 'Moldavië',           hintEasy: 'Wijn',          hintMedium: 'Klein',          hintHard: 'Donau' },
  { categoryId: 'cat-countries', word: 'Georgië',            hintEasy: 'Wijn',          hintMedium: 'Kaukasus',       hintHard: 'Alfabet' },
  { categoryId: 'cat-countries', word: 'Armenië',            hintEasy: 'Cognac',        hintMedium: 'Berg',           hintHard: 'Ararat' },
  { categoryId: 'cat-countries', word: 'Letland',            hintEasy: 'Baltisch',      hintMedium: 'Bos',            hintHard: 'Oranje' },
  { categoryId: 'cat-countries', word: 'Litouwen',           hintEasy: 'Baltisch',      hintMedium: 'Basketbal',      hintHard: 'Barnsten' },
  { categoryId: 'cat-countries', word: 'Estland',            hintEasy: 'Digitaal',      hintMedium: 'Baltisch',       hintHard: 'Skype' },
  { categoryId: 'cat-countries', word: 'Wit-Rusland',        hintEasy: 'Oost-Europa',   hintMedium: 'Diktator',       hintHard: 'Woud' },
  { categoryId: 'cat-countries', word: 'Tanzania',           hintEasy: 'Kilimanjaro',   hintMedium: 'Safari',         hintHard: 'Serengeti' },
  { categoryId: 'cat-countries', word: 'Zuid-Afrika',        hintEasy: 'Diamant',       hintMedium: 'Rugby',          hintHard: 'Regenboog' },
  { categoryId: 'cat-countries', word: 'Madagaskar',         hintEasy: 'Eiland',        hintMedium: 'Lemur',          hintHard: 'Film' },
  { categoryId: 'cat-countries', word: 'Senegal',            hintEasy: 'Voetbal',       hintMedium: 'West-Afrika',    hintHard: 'Teranga' },
  { categoryId: 'cat-countries', word: 'Kameroen',           hintEasy: 'Voetbal',       hintMedium: 'Centraal-Afrika',hintHard: 'Leeuw' },
  { categoryId: 'cat-countries', word: 'DR Congo',           hintEasy: 'Jungle',        hintMedium: 'Rivier',         hintHard: 'Mineraal' },
  { categoryId: 'cat-countries', word: 'Rwanda',             hintEasy: 'Gorilla',       hintMedium: 'Schoon',         hintHard: 'Heuvels' },
  { categoryId: 'cat-countries', word: 'Uganda',             hintEasy: 'Gorilla',       hintMedium: 'Nijl',           hintHard: 'Parel' },
  { categoryId: 'cat-countries', word: 'Zimbabwe',           hintEasy: 'Ruïnes',        hintMedium: 'Biljet',         hintHard: 'Inflatie' },
  { categoryId: 'cat-countries', word: 'Mozambique',         hintEasy: 'Kust',          hintMedium: 'Indische Oceaan',hintHard: 'Cashew' },
  { categoryId: 'cat-countries', word: 'Angola',             hintEasy: 'Olie',          hintMedium: 'Portugees',      hintHard: 'Diamant' },
  { categoryId: 'cat-countries', word: 'Namibië',            hintEasy: 'Woestijn',      hintMedium: 'Duin',           hintHard: 'Skelet' },
  { categoryId: 'cat-countries', word: 'Botswana',           hintEasy: 'Diamant',       hintMedium: 'Okavango',       hintHard: 'Stabiel' },
  { categoryId: 'cat-countries', word: 'Saoedi-Arabië',      hintEasy: 'Olie',          hintMedium: 'Woestijn',       hintHard: 'Mekka' },
  { categoryId: 'cat-countries', word: 'Qatar',              hintEasy: 'WK',            hintMedium: 'Gas',            hintHard: 'Woestijn' },
  { categoryId: 'cat-countries', word: 'VAE',                hintEasy: 'Dubai',         hintMedium: 'Wolkenkrabber',  hintHard: 'Goud' },
  { categoryId: 'cat-countries', word: 'Iran',               hintEasy: 'Perzisch',      hintMedium: 'Olie',           hintHard: 'Tapijt' },
  { categoryId: 'cat-countries', word: 'Irak',               hintEasy: 'Tigris',        hintMedium: 'Bagdad',         hintHard: 'Mesopotamië' },
  { categoryId: 'cat-countries', word: 'Syrië',              hintEasy: 'Conflict',      hintMedium: 'Woestijn',       hintHard: 'Palmyra' },
  { categoryId: 'cat-countries', word: 'Jordanië',           hintEasy: 'Woestijn',      hintMedium: 'Petra',          hintHard: 'Dode Zee' },
  { categoryId: 'cat-countries', word: 'Libanon',            hintEasy: 'Ceder',         hintMedium: 'Middellandse Zee',hintHard: 'Mezze' },
  { categoryId: 'cat-countries', word: 'Jamaica',            hintEasy: 'Reggae',        hintMedium: 'Rum',            hintHard: 'Bolt' },
  { categoryId: 'cat-countries', word: 'Haïti',              hintEasy: 'Eiland',        hintMedium: 'Caribisch',      hintHard: 'Revolutie' },
  { categoryId: 'cat-countries', word: 'Panama',             hintEasy: 'Kanaal',        hintMedium: 'Verbinding',     hintHard: 'Hoed' },
  { categoryId: 'cat-countries', word: 'Costa Rica',         hintEasy: 'Jungle',        hintMedium: 'Pura vida',      hintHard: 'Natuur' },
  { categoryId: 'cat-countries', word: 'Guatemala',          hintEasy: 'Maya',          hintMedium: 'Jungle',         hintHard: 'Koffie' },
  { categoryId: 'cat-countries', word: 'Ecuador',            hintEasy: 'Evenaar',       hintMedium: 'Vulkaan',        hintHard: 'Galapagos' },
  { categoryId: 'cat-countries', word: 'Bolivia',            hintEasy: 'Hoogvlakte',    hintMedium: 'Andes',          hintHard: 'Zoutvlakte' },
  { categoryId: 'cat-countries', word: 'Paraguay',           hintEasy: 'Rivier',        hintMedium: 'Verborgen',      hintHard: 'Guaraní' },
  { categoryId: 'cat-countries', word: 'Uruguay',            hintEasy: 'Rund',          hintMedium: 'Voetbal',        hintHard: 'Tango' },
  { categoryId: 'cat-countries', word: 'Venezuela',          hintEasy: 'Olie',          hintMedium: 'Waterval',       hintHard: 'Bolivar' },
  { categoryId: 'cat-countries', word: 'Suriname',           hintEasy: 'Jungle',        hintMedium: 'Nederlands',     hintHard: 'Paramaribo' },
  { categoryId: 'cat-countries', word: 'Afghanistan',        hintEasy: 'Bergen',        hintMedium: 'Klaproos',       hintHard: 'Zijderoute' },
  { categoryId: 'cat-countries', word: 'Pakistan',           hintEasy: 'Cricket',       hintMedium: 'K2',             hintHard: 'Moessson' },
  { categoryId: 'cat-countries', word: 'Oezbekistan',        hintEasy: 'Zijderoute',    hintMedium: 'Moskee',         hintHard: 'Samarkand' },
  { categoryId: 'cat-countries', word: 'Kazachstan',         hintEasy: 'Steppe',        hintMedium: 'Olie',           hintHard: 'Nomaden' },
  { categoryId: 'cat-countries', word: 'Azerbeidzjan',       hintEasy: 'Vuur',          hintMedium: 'Kaukasus',       hintHard: 'Olie' },
  { categoryId: 'cat-countries', word: 'Turkmenistan',       hintEasy: 'Woestijn',      hintMedium: 'Gas',            hintHard: 'Poort naar hel' },
  { categoryId: 'cat-countries', word: 'Libië',              hintEasy: 'Woestijn',      hintMedium: 'Olie',           hintHard: 'Sahara' },
  { categoryId: 'cat-countries', word: 'Algerije',           hintEasy: 'Sahara',        hintMedium: 'Olie',           hintHard: 'Berbers' },
  { categoryId: 'cat-countries', word: 'Tunesië',            hintEasy: 'Woestijn',      hintMedium: 'Olijven',        hintHard: 'Carthago' },
  { categoryId: 'cat-countries', word: 'Soedan',             hintEasy: 'Nijl',          hintMedium: 'Woestijn',       hintHard: 'Piramide' },
  { categoryId: 'cat-countries', word: 'Ivoorkust',          hintEasy: 'Cacao',         hintMedium: 'Voetbal',        hintHard: 'Ivoor' },
  { categoryId: 'cat-countries', word: 'Mali',               hintEasy: 'Woestijn',      hintMedium: 'Goud',           hintHard: 'Timbuktu' },
  { categoryId: 'cat-countries', word: 'Niger',              hintEasy: 'Sahara',        hintMedium: 'Uranium',        hintHard: 'Tuareg' },
  { categoryId: 'cat-countries', word: 'Zambia',             hintEasy: 'Waterval',      hintMedium: 'Koper',          hintHard: 'Victoria' },
  { categoryId: 'cat-countries', word: 'Malawi',             hintEasy: 'Meer',          hintMedium: 'Vriendelijk',    hintHard: 'Warme hart' },
  { categoryId: 'cat-countries', word: 'Fiji',               hintEasy: 'Eilanden',      hintMedium: 'Tropisch',       hintHard: 'Bula' },
  { categoryId: 'cat-countries', word: 'Papua-Nieuw-Guinea', hintEasy: 'Jungle',        hintMedium: 'Eiland',         hintHard: 'Stammen' },
  { categoryId: 'cat-countries', word: 'Cuba',               hintEasy: 'Sigaar',        hintMedium: 'Rum',            hintHard: 'Revolutie' },
  { categoryId: 'cat-countries', word: 'El Salvador',        hintEasy: 'Bitcoin',       hintMedium: 'Surf',           hintHard: 'Pupusas' },
  { categoryId: 'cat-countries', word: 'Honduras',           hintEasy: 'Banana',        hintMedium: 'Centraal-Amerika',hintHard: 'Mayablauw' },
  { categoryId: 'cat-countries', word: 'Nicaragua',          hintEasy: 'Meren',         hintMedium: 'Koffie',         hintHard: 'Revolutie' },
  { categoryId: 'cat-countries', word: 'Barbados',           hintEasy: 'Caribisch',     hintMedium: 'Rum',            hintHard: 'Rihanna' },
  { categoryId: 'cat-countries', word: 'Trinidad',           hintEasy: 'Caribisch',     hintMedium: 'Staal',          hintHard: 'Carnaval' },
  { categoryId: 'cat-countries', word: 'Luxemburg',          hintEasy: 'Klein',         hintMedium: 'Rijk',           hintHard: 'Kasteel' },
  { categoryId: 'cat-countries', word: 'Noord-Macedonië',    hintEasy: 'Balkan',        hintMedium: 'Alexander',      hintHard: 'Naam' },
  { categoryId: 'cat-countries', word: 'Montenegro',         hintEasy: 'Adriatisch',    hintMedium: 'Fjord',          hintHard: 'Zwarte berg' },
  { categoryId: 'cat-countries', word: 'Kosovo',             hintEasy: 'Jong',          hintMedium: 'Balkan',         hintHard: 'Onafhankelijk' },
  { categoryId: 'cat-countries', word: 'Andorra',            hintEasy: 'Klein',         hintMedium: 'Bergen',         hintHard: 'Skiën' },
  { categoryId: 'cat-countries', word: 'Monaco',             hintEasy: 'Klein',         hintMedium: 'Rijk',           hintHard: 'Casino' },
  { categoryId: 'cat-countries', word: 'Malta',              hintEasy: 'Eiland',        hintMedium: 'Middellandse Zee',hintHard: 'Riddertempel' },
  { categoryId: 'cat-countries', word: 'Cyprus',             hintEasy: 'Eiland',        hintMedium: 'Gedeeld',        hintHard: 'Afrodite' },
  { categoryId: 'cat-countries', word: 'Irak',               hintEasy: 'Tigris',        hintMedium: 'Woestijn',       hintHard: 'Mesopotamië' },
  { categoryId: 'cat-countries', word: 'Laos',               hintEasy: 'Jungle',        hintMedium: 'Mekong',         hintHard: 'Boeddhisme' },
  { categoryId: 'cat-countries', word: 'Brunei',             hintEasy: 'Sultan',        hintMedium: 'Rijk',           hintHard: 'Borneo' },
  { categoryId: 'cat-countries', word: 'Mongolië',           hintEasy: 'Steppe',        hintMedium: 'Nomaden',        hintHard: 'Gengis' },
  { categoryId: 'cat-countries', word: 'Oman',               hintEasy: 'Sultanaat',     hintMedium: 'Arabisch',       hintHard: 'Wierook' },
  { categoryId: 'cat-countries', word: 'Jemen',              hintEasy: 'Arabisch',      hintMedium: 'Conflict',       hintHard: 'Koffie' },
  { categoryId: 'cat-countries', word: 'Koeweit',            hintEasy: 'Olie',          hintMedium: 'Golf',           hintHard: 'Rijkdom' },
  { categoryId: 'cat-countries', word: 'Bahrein',            hintEasy: 'Eiland',        hintMedium: 'Formule 1',      hintHard: 'Parels' },
  { categoryId: 'cat-countries', word: 'Eritrea',            hintEasy: 'Hoorn Afrika',  hintMedium: 'Wielrennen',     hintHard: 'Rood Zee' },
  { categoryId: 'cat-countries', word: 'Somalia',            hintEasy: 'Hoorn Afrika',  hintMedium: 'Piraten',        hintHard: 'Nomaden' },
  { categoryId: 'cat-countries', word: 'Togo',               hintEasy: 'West-Afrika',   hintMedium: 'Kust',           hintHard: 'Palmwijn' },
  { categoryId: 'cat-countries', word: 'Benin',              hintEasy: 'West-Afrika',   hintMedium: 'Voodoo',         hintHard: 'Bronzen koninkrijk' },
  { categoryId: 'cat-countries', word: 'Kameroen',           hintEasy: 'Afrika',        hintMedium: 'Leeuw',          hintHard: 'Bijenkorf' },
  { categoryId: 'cat-countries', word: 'Kaapverdië',         hintEasy: 'Eilanden',      hintMedium: 'Atlantisch',     hintHard: 'Fado' },
  { categoryId: 'cat-countries', word: 'Mauritius',          hintEasy: 'Eiland',        hintMedium: 'Indische Oceaan',hintHard: 'Dodo' },
  { categoryId: 'cat-countries', word: 'Seychellen',         hintEasy: 'Tropisch',      hintMedium: 'Eilanden',       hintHard: 'Graniet' },
  { categoryId: 'cat-countries', word: 'Mozambique',         hintEasy: 'Kust',          hintMedium: 'Portugees',      hintHard: 'Koraalrif' },

  // ─── SPORT +125 ─────────────────────────────────────────────
  { categoryId: 'cat-sports', word: 'Kickboksen',       hintEasy: 'Schoppen',      hintMedium: 'Ring',           hintHard: 'Combinatie' },
  { categoryId: 'cat-sports', word: 'MMA',              hintEasy: 'Kooi',          hintMedium: 'Grijpen',        hintHard: 'Octagon' },
  { categoryId: 'cat-sports', word: 'Jiujitsu',         hintEasy: 'Grijpen',       hintMedium: 'Mat',            hintHard: 'Zwakheden' },
  { categoryId: 'cat-sports', word: 'Aikido',           hintEasy: 'Harmonie',      hintMedium: 'Japan',          hintHard: 'Energie' },
  { categoryId: 'cat-sports', word: 'Capoeira',         hintEasy: 'Dans',          hintMedium: 'Brazilië',       hintHard: 'Vrijheid' },
  { categoryId: 'cat-sports', word: 'Breakdance',       hintEasy: 'Vloer',         hintMedium: 'Muziek',         hintHard: 'Olympisch' },
  { categoryId: 'cat-sports', word: 'Skateboarden',     hintEasy: 'Plank',         hintMedium: 'Truc',           hintHard: 'Gravity' },
  { categoryId: 'cat-sports', word: 'BMX',              hintEasy: 'Fiets',         hintMedium: 'Springen',       hintHard: 'Dirt' },
  { categoryId: 'cat-sports', word: 'Mountainbiken',    hintEasy: 'Berg',          hintMedium: 'Modder',         hintHard: 'Graviteit' },
  { categoryId: 'cat-sports', word: 'Hordenlopen',      hintEasy: 'Springen',      hintMedium: 'Baan',           hintHard: 'Ritme' },
  { categoryId: 'cat-sports', word: 'Verspringen',      hintEasy: 'Zand',          hintMedium: 'Sprong',         hintHard: 'Afzet' },
  { categoryId: 'cat-sports', word: 'Hoogspringen',     hintEasy: 'Lat',           hintMedium: 'Fosbury',        hintHard: 'Zweefvlucht' },
  { categoryId: 'cat-sports', word: 'Polsstokhoogspringen', hintEasy: 'Stok',     hintMedium: 'Hoog',           hintHard: 'Lancering' },
  { categoryId: 'cat-sports', word: 'Kogelstoten',      hintEasy: 'Zwaar',         hintMedium: 'Cirkel',         hintHard: 'Kracht' },
  { categoryId: 'cat-sports', word: 'Discuswerpen',     hintEasy: 'Schijf',        hintMedium: 'Draaien',        hintHard: 'Werpkring' },
  { categoryId: 'cat-sports', word: 'Speerwerpen',      hintEasy: 'Pijl',          hintMedium: 'Werpen',         hintHard: 'Jager' },
  { categoryId: 'cat-sports', word: 'Estafette',        hintEasy: 'Stokje',        hintMedium: 'Team',           hintHard: 'Overdracht' },
  { categoryId: 'cat-sports', word: 'Touwtrekken',      hintEasy: 'Touw',          hintMedium: 'Kracht',         hintHard: 'Lijn' },
  { categoryId: 'cat-sports', word: 'Armworstelen',     hintEasy: 'Arm',           hintMedium: 'Tafel',          hintHard: 'Grip' },
  { categoryId: 'cat-sports', word: 'Ultimate Frisbee', hintEasy: 'Schijf',        hintMedium: 'Veld',           hintHard: 'Teamspel' },
  { categoryId: 'cat-sports', word: 'Softbal',          hintEasy: 'Slagstok',      hintMedium: 'Gooien',         hintHard: 'Onderhands' },
  { categoryId: 'cat-sports', word: 'American football',hintEasy: 'Helm',          hintMedium: 'Touchdown',      hintHard: 'Aanvalsplan' },
  { categoryId: 'cat-sports', word: 'Korfbal',          hintEasy: 'Korf',          hintMedium: 'Gemengd',        hintHard: 'Holland' },
  { categoryId: 'cat-sports', word: 'Netball',          hintEasy: 'Net',           hintMedium: 'Vrouwen',        hintHard: 'Australisch' },
  { categoryId: 'cat-sports', word: 'Polo',             hintEasy: 'Paard',         hintMedium: 'Hamer',          hintHard: 'Adel' },
  { categoryId: 'cat-sports', word: 'Boulderen',        hintEasy: 'Rots',          hintMedium: 'Handen',         hintHard: 'Probleem' },
  { categoryId: 'cat-sports', word: 'Canyoning',        hintEasy: 'Water',         hintMedium: 'Klif',           hintHard: 'Avontuur' },
  { categoryId: 'cat-sports', word: 'Rafting',          hintEasy: 'Boot',          hintMedium: 'Rivier',         hintHard: 'Stroomversnelling' },
  { categoryId: 'cat-sports', word: 'Kitesurfen',       hintEasy: 'Vlieger',       hintMedium: 'Golven',         hintHard: 'Wind' },
  { categoryId: 'cat-sports', word: 'Windsurfen',       hintEasy: 'Zeil',          hintMedium: 'Surfplank',      hintHard: 'Balans' },
  { categoryId: 'cat-sports', word: 'Wakeboarden',      hintEasy: 'Boot',          hintMedium: 'Plank',          hintHard: 'Kabel' },
  { categoryId: 'cat-sports', word: 'Waterskiën',       hintEasy: 'Boot',          hintMedium: 'Ski',            hintHard: 'Slepend' },
  { categoryId: 'cat-sports', word: 'Stand-up paddlen', hintEasy: 'Peddel',        hintMedium: 'Plank',          hintHard: 'Balans' },
  { categoryId: 'cat-sports', word: 'Gewichtheffen',    hintEasy: 'Bar',           hintMedium: 'Zwaar',          hintHard: 'Explosief' },
  { categoryId: 'cat-sports', word: 'Powerlifting',     hintEasy: 'Zwaar',         hintMedium: 'Drie',           hintHard: 'Grendel' },
  { categoryId: 'cat-sports', word: 'Crossfit',         hintEasy: 'Intensief',     hintMedium: 'Box',            hintHard: 'WOD' },
  { categoryId: 'cat-sports', word: 'Ritmische gymnastiek', hintEasy: 'Lint',      hintMedium: 'Muziek',         hintHard: 'Gratie' },
  { categoryId: 'cat-sports', word: 'Trampolinespringen', hintEasy: 'Stuiteren',   hintMedium: 'Lucht',          hintHard: 'Veren' },
  { categoryId: 'cat-sports', word: 'Kunstschaatsen',   hintEasy: 'Draaien',       hintMedium: 'Muziek',         hintHard: 'Figuur' },
  { categoryId: 'cat-sports', word: 'Shorttrack',       hintEasy: 'Ijs',           hintMedium: 'Snel',           hintHard: 'Binnenbocht' },
  { categoryId: 'cat-sports', word: 'Bobslee',          hintEasy: 'Baan',          hintMedium: 'Snel',           hintHard: 'Sturen' },
  { categoryId: 'cat-sports', word: 'Skeleton',         hintEasy: 'Hoofdvoren',    hintMedium: 'Ijs',            hintHard: 'Buikligging' },
  { categoryId: 'cat-sports', word: 'Rodelen',          hintEasy: 'Slee',          hintMedium: 'Berg',           hintHard: 'Voeten' },
  { categoryId: 'cat-sports', word: 'Biathlon',         hintEasy: 'Ski',           hintMedium: 'Geweer',         hintHard: 'Pols' },
  { categoryId: 'cat-sports', word: 'Curling',          hintEasy: 'Steen',         hintMedium: 'Ijs',            hintHard: 'Schoonvegen' },
  { categoryId: 'cat-sports', word: 'Freestyleskiën',   hintEasy: 'Springen',      hintMedium: 'Sneeuw',         hintHard: 'Lucht' },
  { categoryId: 'cat-sports', word: 'Schansspringen',   hintEasy: 'Schans',        hintMedium: 'Vliegen',        hintHard: 'Vleugelstand' },
  { categoryId: 'cat-sports', word: 'Motocross',        hintEasy: 'Motor',         hintMedium: 'Modder',         hintHard: 'Sprong' },
  { categoryId: 'cat-sports', word: 'Rally',            hintEasy: 'Auto',          hintMedium: 'Wegen',          hintHard: 'Co-piloot' },
  { categoryId: 'cat-sports', word: 'Formule 1',        hintEasy: 'Race',          hintMedium: 'Snelheid',       hintHard: 'Pitstop' },
  { categoryId: 'cat-sports', word: 'Karten',           hintEasy: 'Klein',         hintMedium: 'Race',           hintHard: 'Begin' },
  { categoryId: 'cat-sports', word: 'Jetskiën',         hintEasy: 'Water',         hintMedium: 'Snel',           hintHard: 'Golven' },
  { categoryId: 'cat-sports', word: 'Duiken',           hintEasy: 'Fles',          hintMedium: 'Diep',           hintHard: 'Stilte' },
  { categoryId: 'cat-sports', word: 'Freediven',        hintEasy: 'Adem',          hintMedium: 'Diep',           hintHard: 'Rust' },
  { categoryId: 'cat-sports', word: 'Paragliding',      hintEasy: 'Vliegen',       hintMedium: 'Berg',           hintHard: 'Thermiek' },
  { categoryId: 'cat-sports', word: 'Deltavliegen',     hintEasy: 'Vleugels',      hintMedium: 'Wind',           hintHard: 'Deltavorm' },
  { categoryId: 'cat-sports', word: 'Padel',            hintEasy: 'Racket',        hintMedium: 'Glazen wand',    hintHard: 'Duo' },
  { categoryId: 'cat-sports', word: 'Pickleball',       hintEasy: 'Klein',         hintMedium: 'Net',            hintHard: 'Seniorensport' },
  { categoryId: 'cat-sports', word: 'Racquetball',      hintEasy: 'Wand',          hintMedium: 'Rubber',         hintHard: 'Afgesloten' },
  { categoryId: 'cat-sports', word: 'Inline skaten',    hintEasy: 'Wieltjes',      hintMedium: 'Snel',           hintHard: 'Lijn' },
  { categoryId: 'cat-sports', word: 'Rolschaatsen',     hintEasy: 'Wielen',        hintMedium: 'Disco',          hintHard: 'Acht' },
  { categoryId: 'cat-sports', word: 'Baanwielrennen',   hintEasy: 'Fiets',         hintMedium: 'Ovaal',          hintHard: 'Velodroom' },
  { categoryId: 'cat-sports', word: 'Veldrijden',       hintEasy: 'Modder',        hintMedium: 'Fiets',          hintHard: 'Dragen' },
  { categoryId: 'cat-sports', word: 'Synchroonzwemmen', hintEasy: 'Team',          hintMedium: 'Muziek',         hintHard: 'Neusblinker' },
  { categoryId: 'cat-sports', word: 'Kabaddi',          hintEasy: 'Aanraken',      hintMedium: 'India',          hintHard: 'Adem' },
  { categoryId: 'cat-sports', word: 'Sepak Takraw',     hintEasy: 'Voet',          hintMedium: 'Net',            hintHard: 'Rotan' },
  { categoryId: 'cat-sports', word: 'Beachsoccer',      hintEasy: 'Zand',          hintMedium: 'Voetbal',        hintHard: 'Barevoets' },
  { categoryId: 'cat-sports', word: 'Beachvolleybal',   hintEasy: 'Zand',          hintMedium: 'Net',            hintHard: 'Koppeling' },
  { categoryId: 'cat-sports', word: 'Muay Thai',        hintEasy: 'Thailand',      hintMedium: 'Elleboog',       hintHard: 'Achtvoudig' },
  { categoryId: 'cat-sports', word: 'Kendo',            hintEasy: 'Zwaard',        hintMedium: 'Japan',          hintHard: 'Bamboe' },
  { categoryId: 'cat-sports', word: 'Esports',          hintEasy: 'Controller',    hintMedium: 'Online',         hintHard: 'Stadion' },
  { categoryId: 'cat-sports', word: 'Fistbal',          hintEasy: 'Vuist',         hintMedium: 'Net',            hintHard: 'Stuiteren' },
  { categoryId: 'cat-sports', word: 'Floorball',        hintEasy: 'Stick',         hintMedium: 'Hal',            hintHard: 'Plastic' },
  { categoryId: 'cat-sports', word: 'Pentathlon',       hintEasy: 'Vijf',          hintMedium: 'Combinatie',     hintHard: 'Ridder' },
  { categoryId: 'cat-sports', word: 'Decatlon',         hintEasy: 'Tien',          hintMedium: 'Combinatie',     hintHard: 'Allround' },
  { categoryId: 'cat-sports', word: 'Duatlon',          hintEasy: 'Twee',          hintMedium: 'Combinatie',     hintHard: 'Rennen' },
  { categoryId: 'cat-sports', word: 'Sportvissen',      hintEasy: 'Hengel',        hintMedium: 'Geduld',         hintHard: 'Terugplaatsen' },
  { categoryId: 'cat-sports', word: 'Kleiduifschieten', hintEasy: 'Schiet',        hintMedium: 'Vliegend',       hintHard: 'Trap' },
  { categoryId: 'cat-sports', word: 'Ballonvaren',      hintEasy: 'Lucht',         hintMedium: 'Vlammen',        hintHard: 'Drijven' },
  { categoryId: 'cat-sports', word: 'Slopestyle',       hintEasy: 'Springen',      hintMedium: 'Piste',          hintHard: 'Stijl' },
  { categoryId: 'cat-sports', word: 'Halfpipe',         hintEasy: 'U-vorm',        hintMedium: 'Sneeuw',         hintHard: 'Lucht' },
  { categoryId: 'cat-sports', word: 'Enduro',           hintEasy: 'Motor',         hintMedium: 'Off-road',       hintHard: 'Uithouding' },
  { categoryId: 'cat-sports', word: 'Sneeuwschoenlopen',hintEasy: 'Sneeuw',        hintMedium: 'Breed',          hintHard: 'Drijven' },
  { categoryId: 'cat-sports', word: 'Oriëntatielopen',  hintEasy: 'Kaart',         hintMedium: 'Bos',            hintHard: 'Kompas' },
  { categoryId: 'cat-sports', word: 'Mudrun',           hintEasy: 'Modder',        hintMedium: 'Hindernissen',   hintHard: 'Teamwork' },
  { categoryId: 'cat-sports', word: 'Dragonboat',       hintEasy: 'Draak',         hintMedium: 'Peddelen',       hintHard: 'Trommel' },
  { categoryId: 'cat-sports', word: 'Speedklimmen',     hintEasy: 'Muur',          hintMedium: 'Snel',           hintHard: 'Touw' },
  { categoryId: 'cat-sports', word: 'Longboarden',      hintEasy: 'Lang',          hintMedium: 'Rijden',         hintHard: 'Afdalen' },
  { categoryId: 'cat-sports', word: 'Kajakken',         hintEasy: 'Peddel',        hintMedium: 'Smal',           hintHard: 'Rollen' },
  { categoryId: 'cat-sports', word: 'Triatlon',         hintEasy: 'Drie',          hintMedium: 'Zwemmen',        hintHard: 'Uithouding' },
  { categoryId: 'cat-sports', word: 'Freerunning',      hintEasy: 'Stad',          hintMedium: 'Springen',       hintHard: 'Stroom' },
  { categoryId: 'cat-sports', word: 'Snowkiten',        hintEasy: 'Vlieger',       hintMedium: 'Sneeuw',         hintHard: 'Wind' },
  { categoryId: 'cat-sports', word: 'Wakesurf',         hintEasy: 'Golf',          hintMedium: 'Boot',           hintHard: 'Slipstream' },
  { categoryId: 'cat-sports', word: 'Bungejumpen',      hintEasy: 'Touw',          hintMedium: 'Hoogte',         hintHard: 'Elastiek' },
  { categoryId: 'cat-sports', word: 'Mountainklimmen',  hintEasy: 'Touw',          hintMedium: 'Bergen',         hintHard: 'Bivak' },
  { categoryId: 'cat-sports', word: 'Speleologie',      hintEasy: 'Grot',          hintMedium: 'Donker',         hintHard: 'Kaart' },
  { categoryId: 'cat-sports', word: 'Langeafstandslopen',hintEasy: 'Schoenen',     hintMedium: 'Uithouding',     hintHard: 'Kilometers' },
  { categoryId: 'cat-sports', word: 'Trailrunning',     hintEasy: 'Pad',           hintMedium: 'Berg',           hintHard: 'Terrein' },
  { categoryId: 'cat-sports', word: 'Aquajoggen',       hintEasy: 'Water',         hintMedium: 'Bewegen',        hintHard: 'Drijven' },
  { categoryId: 'cat-sports', word: 'Zumba',            hintEasy: 'Dans',          hintMedium: 'Muziek',         hintHard: 'Latijn' },
]
