// Extra words: Muziek (125) + Natuur (125)

export const extraWords4 = [

  // ─── MUZIEK +125 ────────────────────────────────────────────
  { categoryId: 'cat-music', word: 'R&B',               hintEasy: 'Soul',          hintMedium: 'Ritme',          hintHard: 'Groove' },
  { categoryId: 'cat-music', word: 'Soul',              hintEasy: 'Gevoel',        hintMedium: 'Amerika',        hintHard: 'Gospel' },
  { categoryId: 'cat-music', word: 'Funk',              hintEasy: 'Bas',           hintMedium: 'Groove',         hintHard: 'Ritmisch' },
  { categoryId: 'cat-music', word: 'Disco',             hintEasy: 'Dansen',        hintMedium: 'Jaren 70',       hintHard: 'Bol' },
  { categoryId: 'cat-music', word: 'House',             hintEasy: 'Electronica',   hintMedium: 'Club',           hintHard: 'Four-on-the-floor' },
  { categoryId: 'cat-music', word: 'Techno',            hintEasy: 'Elektronisch',  hintMedium: 'Hard',           hintHard: 'Detroit' },
  { categoryId: 'cat-music', word: 'Trance',            hintEasy: 'Herhalend',     hintMedium: 'Reizen',         hintHard: 'Opbouwen' },
  { categoryId: 'cat-music', word: 'Drum and bass',     hintEasy: 'Snel',          hintMedium: 'Elektronisch',   hintHard: 'Gebroken' },
  { categoryId: 'cat-music', word: 'Dubstep',           hintEasy: 'Drop',          hintMedium: 'Bas',            hintHard: 'Wiggelen' },
  { categoryId: 'cat-music', word: 'EDM',               hintEasy: 'Elektronisch',  hintMedium: 'Festival',       hintHard: 'Drop' },
  { categoryId: 'cat-music', word: 'Metal',             hintEasy: 'Gitaar',        hintMedium: 'Hard',           hintHard: 'Screamen' },
  { categoryId: 'cat-music', word: 'Punk',              hintEasy: 'Rebel',         hintMedium: 'Snel',           hintHard: 'Anarchie' },
  { categoryId: 'cat-music', word: 'Indie',             hintEasy: 'Onafhankelijk', hintMedium: 'Alternatief',    hintHard: 'Eigen label' },
  { categoryId: 'cat-music', word: 'Folk',              hintEasy: 'Akoestisch',    hintMedium: 'Volkslied',      hintHard: 'Traditie' },
  { categoryId: 'cat-music', word: 'Country',           hintEasy: 'Gitaar',        hintMedium: 'Amerika',        hintHard: 'Cowboy' },
  { categoryId: 'cat-music', word: 'Gospel',            hintEasy: 'Kerk',          hintMedium: 'Koor',           hintHard: 'Vreugde' },
  { categoryId: 'cat-music', word: 'Latin',             hintEasy: 'Dansen',        hintMedium: 'Ritme',          hintHard: 'Passie' },
  { categoryId: 'cat-music', word: 'Salsa',             hintEasy: 'Dansen',        hintMedium: 'Cuba',           hintHard: 'Kruid' },
  { categoryId: 'cat-music', word: 'Bachata',           hintEasy: 'Dansen',        hintMedium: 'Dominicaans',    hintHard: 'Intiem' },
  { categoryId: 'cat-music', word: 'Bossa nova',        hintEasy: 'Rustig',        hintMedium: 'Brazilië',       hintHard: 'Ipanema' },
  { categoryId: 'cat-music', word: 'Flamenco',          hintEasy: 'Spaans',        hintMedium: 'Voeten',         hintHard: 'Vuur' },
  { categoryId: 'cat-music', word: 'K-pop',             hintEasy: 'Korea',         hintMedium: 'Dans',           hintHard: 'Fandom' },
  { categoryId: 'cat-music', word: 'Rap',               hintEasy: 'Tekst',         hintMedium: 'Ritme',          hintHard: 'Straat' },
  { categoryId: 'cat-music', word: 'Trap',              hintEasy: 'Beat',          hintMedium: 'Hi-hat',         hintHard: 'Drugsreferentie' },
  { categoryId: 'cat-music', word: 'Lo-fi',             hintEasy: 'Rustig',        hintMedium: 'Studeren',       hintHard: 'Ruis' },
  { categoryId: 'cat-music', word: 'Synthesizer',       hintEasy: 'Knoppen',       hintMedium: 'Klanken maken',  hintHard: 'Oscillator' },
  { categoryId: 'cat-music', word: 'Drumcomputer',      hintEasy: 'Ritme',         hintMedium: 'Programmeren',   hintHard: 'Grid' },
  { categoryId: 'cat-music', word: 'Sample',            hintEasy: 'Fragment',      hintMedium: 'Hergebruiken',   hintHard: 'Oorsprong' },
  { categoryId: 'cat-music', word: 'Beat',              hintEasy: 'Ritme',         hintMedium: 'Kloppen',        hintHard: 'Fundering' },
  { categoryId: 'cat-music', word: 'Solo',              hintEasy: 'Alleen',        hintMedium: 'Instrument',     hintHard: 'Spotlight' },
  { categoryId: 'cat-music', word: 'Duet',              hintEasy: 'Twee',          hintMedium: 'Samen',          hintHard: 'Harmonie' },
  { categoryId: 'cat-music', word: 'Band',              hintEasy: 'Groep',         hintMedium: 'Muzikanten',     hintHard: 'Chemie' },
  { categoryId: 'cat-music', word: 'Componist',         hintEasy: 'Schrijven',     hintMedium: 'Noten',          hintHard: 'Erfenis' },
  { categoryId: 'cat-music', word: 'Arrangeur',         hintEasy: 'Instrumenten',  hintMedium: 'Verdelen',       hintHard: 'Laagjes' },
  { categoryId: 'cat-music', word: 'Tekstschrijver',    hintEasy: 'Woorden',       hintMedium: 'Refrein',        hintHard: 'Gevoel' },
  { categoryId: 'cat-music', word: 'Streaming',         hintEasy: 'Online',        hintMedium: 'Luisteren',      hintHard: 'Algoritme' },
  { categoryId: 'cat-music', word: 'Playlist',          hintEasy: 'Nummers',       hintMedium: 'Volgorde',       hintHard: 'Sfeer' },
  { categoryId: 'cat-music', word: 'Vinyl',             hintEasy: 'Plaat',         hintMedium: 'Naald',          hintHard: 'Nostalgie' },
  { categoryId: 'cat-music', word: 'Tournee',           hintEasy: 'Reizen',        hintMedium: 'Optreden',       hintHard: 'Uitverkopen' },
  { categoryId: 'cat-music', word: 'Backstage',         hintEasy: 'Achter',        hintMedium: 'Artiest',        hintHard: 'Exclusief' },
  { categoryId: 'cat-music', word: 'Encore',            hintEasy: 'Meer',          hintMedium: 'Publiek',        hintHard: 'Klappen' },
  { categoryId: 'cat-music', word: 'Refrein',           hintEasy: 'Herhalen',      hintMedium: 'Lied',           hintHard: 'Blijft hangen' },
  { categoryId: 'cat-music', word: 'Couplet',           hintEasy: 'Deel',          hintMedium: 'Tekst',          hintHard: 'Verhaal' },
  { categoryId: 'cat-music', word: 'Intro',             hintEasy: 'Begin',         hintMedium: 'Binnenkomst',    hintHard: 'Verwachting' },
  { categoryId: 'cat-music', word: 'Riff',              hintEasy: 'Gitaar',        hintMedium: 'Herhalend',      hintHard: 'Herkenbaar' },
  { categoryId: 'cat-music', word: 'Groove',            hintEasy: 'Bewegen',       hintMedium: 'Ritme',          hintHard: 'Voelen' },
  { categoryId: 'cat-music', word: 'Swing',             hintEasy: 'Jazz',          hintMedium: 'Dansen',         hintHard: 'Off-beat' },
  { categoryId: 'cat-music', word: 'Acapella',          hintEasy: 'Stem',          hintMedium: 'Zonder',         hintHard: 'Puur' },
  { categoryId: 'cat-music', word: 'Beatboxen',         hintEasy: 'Mond',          hintMedium: 'Ritme',          hintHard: 'Trommel' },
  { categoryId: 'cat-music', word: 'Remix',             hintEasy: 'Aanpassen',     hintMedium: 'DJ',             hintHard: 'Nieuw leven' },
  { categoryId: 'cat-music', word: 'Cover',             hintEasy: 'Natelen',       hintMedium: 'Origineel',      hintHard: 'Eer' },
  { categoryId: 'cat-music', word: 'Opnamestudio',      hintEasy: 'Opnemen',       hintMedium: 'Geluidsdicht',   hintHard: 'Geluid vangen' },
  { categoryId: 'cat-music', word: 'Soundcheck',        hintEasy: 'Testen',        hintMedium: 'Podium',         hintHard: 'Voor het concert' },
  { categoryId: 'cat-music', word: 'Reverb',            hintEasy: 'Echo',          hintMedium: 'Ruimte',         hintHard: 'Nagalm' },
  { categoryId: 'cat-music', word: 'Distortion',        hintEasy: 'Vervormd',      hintMedium: 'Gitaar',         hintHard: 'Ruw' },
  { categoryId: 'cat-music', word: 'Metronoom',         hintEasy: 'Tikken',        hintMedium: 'Tempo',          hintHard: 'Slingerend' },
  { categoryId: 'cat-music', word: 'Akkoord',           hintEasy: 'Noten samen',   hintMedium: 'Gitaar',         hintHard: 'Klankkleur' },
  { categoryId: 'cat-music', word: 'Toonladder',        hintEasy: 'Noten',         hintMedium: 'Volgorde',       hintHard: 'Ladder' },
  { categoryId: 'cat-music', word: 'Octaaf',            hintEasy: 'Acht',          hintMedium: 'Hoog-laag',      hintHard: 'Frequentie' },
  { categoryId: 'cat-music', word: 'Crescendo',         hintEasy: 'Harder',        hintMedium: 'Opbouwen',       hintHard: 'Klimmen' },
  { categoryId: 'cat-music', word: 'Vibrato',           hintEasy: 'Trillen',       hintMedium: 'Stem',           hintHard: 'Oscilleren' },
  { categoryId: 'cat-music', word: 'Pizzicato',         hintEasy: 'Snaar',         hintMedium: 'Plukken',        hintHard: 'Tik' },
  { categoryId: 'cat-music', word: 'Arpeggio',          hintEasy: 'Noten',         hintMedium: 'Na elkaar',      hintHard: 'Waterval' },
  { categoryId: 'cat-music', word: 'Hitlijst',          hintEasy: 'Top 40',        hintMedium: 'Populair',       hintHard: 'Positie' },
  { categoryId: 'cat-music', word: 'Grammy',            hintEasy: 'Award',         hintMedium: 'Muziek',         hintHard: 'Grammofoon' },
  { categoryId: 'cat-music', word: 'Muziekvideo',       hintEasy: 'Clip',          hintMedium: 'Visueel',        hintHard: 'Verhaal' },
  { categoryId: 'cat-music', word: 'Moshpit',           hintEasy: 'Cirkel',        hintMedium: 'Concert',        hintHard: 'Chaos' },
  { categoryId: 'cat-music', word: 'Fanbase',           hintEasy: 'Fans',          hintMedium: 'Trouwe',         hintHard: 'Gemeenschap' },
  { categoryId: 'cat-music', word: 'Setlist',           hintEasy: 'Volgorde',      hintMedium: 'Concert',        hintHard: 'Verrassing' },
  { categoryId: 'cat-music', word: 'Soundbite',         hintEasy: 'Fragment',      hintMedium: 'Herkenbaar',     hintHard: 'Vangen' },
  { categoryId: 'cat-music', word: 'Beatmaken',         hintEasy: 'Produceren',    hintMedium: 'Computer',       hintHard: 'Creatief' },
  { categoryId: 'cat-music', word: 'Loopstation',       hintEasy: 'Herhalen',      hintMedium: 'Layers',         hintHard: 'Live' },
  { categoryId: 'cat-music', word: 'Equalizer',         hintEasy: 'Knoppen',       hintMedium: 'Geluid bijstellen', hintHard: 'Frequentie' },
  { categoryId: 'cat-music', word: 'Basslijn',          hintEasy: 'Laag',          hintMedium: 'Ritme',          hintHard: 'Fundament' },
  { categoryId: 'cat-music', word: 'Drumkit',           hintEasy: 'Slagwerk',      hintMedium: 'Trommen',        hintHard: 'Opstelling' },
  { categoryId: 'cat-music', word: 'Klagende blues',    hintEasy: 'Droefheid',     hintMedium: 'Gitaar',         hintHard: 'Ziel' },
  { categoryId: 'cat-music', word: 'Punk rock',         hintEasy: 'Rebel',         hintMedium: 'Gitaar',         hintHard: 'Drie akkoorden' },
  { categoryId: 'cat-music', word: 'Afrobeats',         hintEasy: 'Afrika',        hintMedium: 'Dansen',         hintHard: 'Percussie' },
  { categoryId: 'cat-music', word: 'Reggaeton',         hintEasy: 'Latino',        hintMedium: 'Dansen',         hintHard: 'Dembow' },
  { categoryId: 'cat-music', word: 'Ambient',           hintEasy: 'Rustig',        hintMedium: 'Achtergrond',    hintHard: 'Atmosfeer' },
  { categoryId: 'cat-music', word: 'Eurodance',         hintEasy: 'Dansen',        hintMedium: 'Jaren 90',       hintHard: 'Synth' },
  { categoryId: 'cat-music', word: 'Bluegrass',         hintEasy: 'Banjo',         hintMedium: 'Amerika',        hintHard: 'Berg' },
  { categoryId: 'cat-music', word: 'New wave',          hintEasy: 'Jaren 80',      hintMedium: 'Synthesizer',    hintHard: 'Post-punk' },
  { categoryId: 'cat-music', word: 'Electropop',        hintEasy: 'Synthesizer',   hintMedium: 'Zingen',         hintHard: 'Dromerig' },
  { categoryId: 'cat-music', word: 'Grunge',            hintEasy: 'Seattle',       hintMedium: 'Gitaar',         hintHard: 'Generatie X' },
  { categoryId: 'cat-music', word: 'Alternative',       hintEasy: 'Anders',        hintMedium: 'Gitaar',         hintHard: 'Mainstream vermijden' },
  { categoryId: 'cat-music', word: 'Hard rock',         hintEasy: 'Luid',          hintMedium: 'Gitaar',         hintHard: 'Kracht' },
  { categoryId: 'cat-music', word: 'Progressieve rock', hintEasy: 'Lang',          hintMedium: 'Ingewikkeld',    hintHard: 'Episch' },
  { categoryId: 'cat-music', word: 'Songfestival',      hintEasy: 'Europa',        hintMedium: 'Zingen',         hintHard: 'Jury' },
  { categoryId: 'cat-music', word: 'Ballad',            hintEasy: 'Langzaam',      hintMedium: 'Gevoel',         hintHard: 'Verhaal' },
  { categoryId: 'cat-music', word: 'Uptempo',           hintEasy: 'Snel',          hintMedium: 'Energie',        hintHard: 'BPM' },
  { categoryId: 'cat-music', word: 'Soundscape',        hintEasy: 'Sfeer',         hintMedium: 'Omgeving',       hintHard: 'Imersief' },
  { categoryId: 'cat-music', word: 'Muziekbox',         hintEasy: 'Muziek',        hintMedium: 'Munt',           hintHard: 'Bar' },
  { categoryId: 'cat-music', word: 'Cassettebandje',    hintEasy: 'Oud',           hintMedium: 'Opname',         hintHard: 'Terugspoelen' },
  { categoryId: 'cat-music', word: 'Walkman',           hintEasy: 'Onderweg',      hintMedium: 'Cassette',       hintHard: 'Jaren 80' },
  { categoryId: 'cat-music', word: 'iPod',              hintEasy: 'Muziek',        hintMedium: 'Pocket',         hintHard: 'Wieltje' },
  { categoryId: 'cat-music', word: 'Headbangen',        hintEasy: 'Hoofd',         hintMedium: 'Metal',          hintHard: 'Ritme' },
  { categoryId: 'cat-music', word: 'Air guitar',        hintEasy: 'Doen alsof',    hintMedium: 'Gitaar',         hintHard: 'Speels' },
  { categoryId: 'cat-music', word: 'Lipsync',           hintEasy: 'Lippen',        hintMedium: 'Nep',            hintHard: 'Perfecte timing' },
  { categoryId: 'cat-music', word: 'Muziekschool',      hintEasy: 'Leren',         hintMedium: 'Noten',          hintHard: 'Conservatorium' },
  { categoryId: 'cat-music', word: 'Optocht',           hintEasy: 'Lopen',         hintMedium: 'Muziek',         hintHard: 'Straat' },

  // ─── NATUUR +125 ────────────────────────────────────────────
  { categoryId: 'cat-nature', word: 'Planeet',          hintEasy: 'Ruimte',        hintMedium: 'Draaien',        hintHard: 'Baan' },
  { categoryId: 'cat-nature', word: 'Mars',             hintEasy: 'Rood',          hintMedium: 'Ruimte',         hintHard: 'Rovers' },
  { categoryId: 'cat-nature', word: 'Jupiter',          hintEasy: 'Groot',         hintMedium: 'Stormen',        hintHard: 'Gasreus' },
  { categoryId: 'cat-nature', word: 'Venus',            hintEasy: 'Heet',          hintMedium: 'Planeet',        hintHard: 'Giftig' },
  { categoryId: 'cat-nature', word: 'Saturnus',         hintEasy: 'Ringen',        hintMedium: 'Planeet',        hintHard: 'Gasreus' },
  { categoryId: 'cat-nature', word: 'Melkweg',          hintEasy: 'Sterren',       hintMedium: 'Spiraal',        hintHard: 'Wolk' },
  { categoryId: 'cat-nature', word: 'Zwart gat',        hintEasy: 'Donker',        hintMedium: 'Aantrekken',     hintHard: 'Geen ontsnapping' },
  { categoryId: 'cat-nature', word: 'Supernova',        hintEasy: 'Explosie',      hintMedium: 'Ster',           hintHard: 'Stof' },
  { categoryId: 'cat-nature', word: 'Ster',             hintEasy: 'Licht',         hintMedium: 'Nacht',          hintHard: 'Kernfusie' },
  { categoryId: 'cat-nature', word: 'Atmosfeer',        hintEasy: 'Lucht',         hintMedium: 'Bescherming',    hintHard: 'Lagen' },
  { categoryId: 'cat-nature', word: 'Ozonlaag',         hintEasy: 'Bescherming',   hintMedium: 'UV',             hintHard: 'Gat' },
  { categoryId: 'cat-nature', word: 'Magnetisch veld',  hintEasy: 'Kompas',        hintMedium: 'Aarde',          hintHard: 'Schild' },
  { categoryId: 'cat-nature', word: 'Getijden',         hintEasy: 'Water',         hintMedium: 'Maan',           hintHard: 'Eb en vloed' },
  { categoryId: 'cat-nature', word: 'Golfstroom',       hintEasy: 'Warme stroom',  hintMedium: 'Oceaan',         hintHard: 'Europa' },
  { categoryId: 'cat-nature', word: 'Moesson',          hintEasy: 'Regen',         hintMedium: 'Azië',           hintHard: 'Seizoen' },
  { categoryId: 'cat-nature', word: 'Cycloon',          hintEasy: 'Wind',          hintMedium: 'Draaiend',       hintHard: 'Oog' },
  { categoryId: 'cat-nature', word: 'Orkan',            hintEasy: 'Krachtige wind',hintMedium: 'Oceaan',         hintHard: 'Naam' },
  { categoryId: 'cat-nature', word: 'Sneeuwstorm',      hintEasy: 'Wit',           hintMedium: 'Winter',         hintHard: 'Zichtbaar' },
  { categoryId: 'cat-nature', word: 'Dooi',             hintEasy: 'Smeltend',      hintMedium: 'Lente',          hintHard: 'Drup' },
  { categoryId: 'cat-nature', word: 'IJspegel',         hintEasy: 'Ijs',           hintMedium: 'Dak',            hintHard: 'Druppelen' },
  { categoryId: 'cat-nature', word: 'Rijp',             hintEasy: 'Wit',           hintMedium: 'Ochtend',        hintHard: 'Kristal' },
  { categoryId: 'cat-nature', word: 'Vorst',            hintEasy: 'Koud',          hintMedium: 'Winter',         hintHard: 'Bevriezen' },
  { categoryId: 'cat-nature', word: 'Herfst',           hintEasy: 'Bladeren',      hintMedium: 'Kleuren',        hintHard: 'Vergankelijk' },
  { categoryId: 'cat-nature', word: 'Lente',            hintEasy: 'Bloemen',       hintMedium: 'Nieuw',          hintHard: 'Ontwaken' },
  { categoryId: 'cat-nature', word: 'Zomer',            hintEasy: 'Warm',          hintMedium: 'Vakantie',       hintHard: 'Zenit' },
  { categoryId: 'cat-nature', word: 'Winter',           hintEasy: 'Koud',          hintMedium: 'Sneeuw',         hintHard: 'Rust' },
  { categoryId: 'cat-nature', word: 'Wervelwind',       hintEasy: 'Draaien',       hintMedium: 'Wind',           hintHard: 'Stof' },
  { categoryId: 'cat-nature', word: 'Zandstorm',        hintEasy: 'Zand',          hintMedium: 'Woestijn',       hintHard: 'Verstikken' },
  { categoryId: 'cat-nature', word: 'IJsberg',          hintEasy: 'Ijs',           hintMedium: 'Oceaan',         hintHard: 'Verborgen' },
  { categoryId: 'cat-nature', word: 'Noordpool',        hintEasy: 'Ijs',           hintMedium: 'Poolbeer',       hintHard: 'Middernachtzon' },
  { categoryId: 'cat-nature', word: 'Zuidpool',         hintEasy: 'Sneeuw',        hintMedium: 'Pinguïn',        hintHard: 'Extreme kou' },
  { categoryId: 'cat-nature', word: 'Taiga',            hintEasy: 'Dennenbos',     hintMedium: 'Rusland',        hintHard: 'Koud bos' },
  { categoryId: 'cat-nature', word: 'Steppe',           hintEasy: 'Gras',          hintMedium: 'Mongolië',       hintHard: 'Eindeloos' },
  { categoryId: 'cat-nature', word: 'Pampa',            hintEasy: 'Gras',          hintMedium: 'Argentinië',     hintHard: 'Gaucho' },
  { categoryId: 'cat-nature', word: 'Prairie',          hintEasy: 'Gras',          hintMedium: 'Amerika',        hintHard: 'Bizon' },
  { categoryId: 'cat-nature', word: 'Mangrovebos',      hintEasy: 'Wortels',       hintMedium: 'Water',          hintHard: 'Kust' },
  { categoryId: 'cat-nature', word: 'Veen',             hintEasy: 'Donker',        hintMedium: 'Nat',            hintHard: 'Brandstof' },
  { categoryId: 'cat-nature', word: 'Heide',            hintEasy: 'Paars',         hintMedium: 'Droog',          hintHard: 'Bloei' },
  { categoryId: 'cat-nature', word: 'Duinen',           hintEasy: 'Zand',          hintMedium: 'Kust',           hintHard: 'Golvend' },
  { categoryId: 'cat-nature', word: 'Klif',             hintEasy: 'Steil',         hintMedium: 'Zee',            hintHard: 'Erosie' },
  { categoryId: 'cat-nature', word: 'Delta',            hintEasy: 'Rivier',        hintMedium: 'Zee',            hintHard: 'Verspreiden' },
  { categoryId: 'cat-nature', word: 'Lagune',           hintEasy: 'Stilwater',     hintMedium: 'Kust',           hintHard: 'Barrière' },
  { categoryId: 'cat-nature', word: 'Atol',             hintEasy: 'Ring',          hintMedium: 'Oceaan',         hintHard: 'Koraal' },
  { categoryId: 'cat-nature', word: 'Canyon',           hintEasy: 'Kloof',         hintMedium: 'Rots',           hintHard: 'Erosie' },
  { categoryId: 'cat-nature', word: 'Plateau',          hintEasy: 'Vlak',          hintMedium: 'Hoog',           hintHard: 'Tafelberg' },
  { categoryId: 'cat-nature', word: 'Lava',             hintEasy: 'Heet',          hintMedium: 'Vloeien',        hintHard: 'Basalt' },
  { categoryId: 'cat-nature', word: 'Krater',           hintEasy: 'Ronde holte',   hintMedium: 'Vulkaan',        hintHard: 'Inslag' },
  { categoryId: 'cat-nature', word: 'Caldera',          hintEasy: 'Grote holte',   hintMedium: 'Vulkaan',        hintHard: 'Ingestort' },
  { categoryId: 'cat-nature', word: 'Warmwaterbron',    hintEasy: 'Warm',          hintMedium: 'Aarde',          hintHard: 'Ontspannen' },
  { categoryId: 'cat-nature', word: 'Zoutvlakte',       hintEasy: 'Wit',           hintMedium: 'Droog',          hintHard: 'Bolivia' },
  { categoryId: 'cat-nature', word: 'Gesteente',        hintEasy: 'Steen',         hintMedium: 'Aarde',          hintHard: 'Lagen' },
  { categoryId: 'cat-nature', word: 'Mineraal',         hintEasy: 'Steen',         hintMedium: 'Kristal',        hintHard: 'Mijnbouw' },
  { categoryId: 'cat-nature', word: 'Edelsteen',        hintEasy: 'Glinsteren',    hintMedium: 'Waarde',         hintHard: 'Slijpen' },
  { categoryId: 'cat-nature', word: 'Graniet',          hintEasy: 'Hard',          hintMedium: 'Keuken',         hintHard: 'Magma' },
  { categoryId: 'cat-nature', word: 'Marmer',           hintEasy: 'Glanzend',      hintMedium: 'Vloer',          hintHard: 'Metamorf' },
  { categoryId: 'cat-nature', word: 'Kalksteen',        hintEasy: 'Wit',           hintMedium: 'Grotten',        hintHard: 'Kool' },
  { categoryId: 'cat-nature', word: 'Obsidiaan',        hintEasy: 'Zwart',         hintMedium: 'Vulkaan',        hintHard: 'Scherp' },
  { categoryId: 'cat-nature', word: 'Kwarts',           hintEasy: 'Transparant',   hintMedium: 'Kristal',        hintHard: 'Horloge' },
  { categoryId: 'cat-nature', word: 'Diamant',          hintEasy: 'Hard',          hintMedium: 'Ring',           hintHard: 'Druk' },
  { categoryId: 'cat-nature', word: 'Zeewier',          hintEasy: 'Groen',         hintMedium: 'Zee',            hintHard: 'Voeding' },
  { categoryId: 'cat-nature', word: 'Plankton',         hintEasy: 'Klein',         hintMedium: 'Zee',            hintHard: 'Fundament' },
  { categoryId: 'cat-nature', word: 'Koraal',           hintEasy: 'Kleur',         hintMedium: 'Zee',            hintHard: 'Levend' },
  { categoryId: 'cat-nature', word: 'Fossiel',          hintEasy: 'Oud',           hintMedium: 'Steen',          hintHard: 'Ingebed' },
  { categoryId: 'cat-nature', word: 'Zwavel',           hintEasy: 'Geel',          hintMedium: 'Stinkend',       hintHard: 'Vulkaan' },
  { categoryId: 'cat-nature', word: 'Aardolie',         hintEasy: 'Zwart',         hintMedium: 'Vloeibaar',      hintHard: 'Fossiel' },
  { categoryId: 'cat-nature', word: 'Kool',             hintEasy: 'Zwart',         hintMedium: 'Oud',            hintHard: 'Druk' },
  { categoryId: 'cat-nature', word: 'Aardgas',          hintEasy: 'Onzichtbaar',   hintMedium: 'Energie',        hintHard: 'Koken' },
  { categoryId: 'cat-nature', word: 'Toendra',          hintEasy: 'Koud',          hintMedium: 'Vlak',           hintHard: 'Permafrost' },
  { categoryId: 'cat-nature', word: 'Poolster',         hintEasy: 'Nacht',         hintMedium: 'Navigeren',      hintHard: 'Vast punt' },
  { categoryId: 'cat-nature', word: 'Horizon',          hintEasy: 'Ver',           hintMedium: 'Lijn',           hintHard: 'Bereikbaar?' },
  { categoryId: 'cat-nature', word: 'Zonsverduistering', hintEasy: 'Donker',      hintMedium: 'Maan',           hintHard: 'Kortstondig' },
  { categoryId: 'cat-nature', word: 'Maansverduistering', hintEasy: 'Schaduw',    hintMedium: 'Aarde',          hintHard: 'Bloedrood' },
  { categoryId: 'cat-nature', word: 'Komeetenstaart',   hintEasy: 'Staart',        hintMedium: 'Ruimte',         hintHard: 'Ijs' },
  { categoryId: 'cat-nature', word: 'Sterrenregen',     hintEasy: 'Vallen',        hintMedium: 'Nacht',          hintHard: 'Wens' },
  { categoryId: 'cat-nature', word: 'Nevel',            hintEasy: 'Ruimte',        hintMedium: 'Wolken',         hintHard: 'Geboortegrond' },
  { categoryId: 'cat-nature', word: 'Zeekust',          hintEasy: 'Strand',        hintMedium: 'Golven',         hintHard: 'Grenslijn' },
  { categoryId: 'cat-nature', word: 'Estuarium',        hintEasy: 'Rivier',        hintMedium: 'Zee',            hintHard: 'Zout-zoet' },
  { categoryId: 'cat-nature', word: 'Bron',             hintEasy: 'Water',         hintMedium: 'Grond',          hintHard: 'Begin' },
  { categoryId: 'cat-nature', word: 'Waterput',         hintEasy: 'Graven',        hintMedium: 'Water',          hintHard: 'Diepte' },
  { categoryId: 'cat-nature', word: 'Rivier',           hintEasy: 'Stromen',       hintMedium: 'Oever',          hintHard: 'Bron' },
  { categoryId: 'cat-nature', word: 'Beek',             hintEasy: 'Klein',         hintMedium: 'Kabbelen',       hintHard: 'Helder' },
  { categoryId: 'cat-nature', word: 'Waterrad',         hintEasy: 'Draaien',       hintMedium: 'Rivier',         hintHard: 'Energie' },
  { categoryId: 'cat-nature', word: 'Ijskap',           hintEasy: 'Ijs',           hintMedium: 'Pool',           hintHard: 'Smelten' },
  { categoryId: 'cat-nature', word: 'Sneeuwtop',        hintEasy: 'Berg',          hintMedium: 'Wit',            hintHard: 'Hoogte' },
  { categoryId: 'cat-nature', word: 'Lawine',           hintEasy: 'Sneeuw',        hintMedium: 'Berg',           hintHard: 'Gevaar' },
  { categoryId: 'cat-nature', word: 'Modderstromen',    hintEasy: 'Modder',        hintMedium: 'Regen',          hintHard: 'Verslikken' },
  { categoryId: 'cat-nature', word: 'Bosbranden',       hintEasy: 'Vuur',          hintMedium: 'Bos',            hintHard: 'Rook' },
  { categoryId: 'cat-nature', word: 'Corrosie',         hintEasy: 'Roest',         hintMedium: 'Metaal',         hintHard: 'Aantasting' },
  { categoryId: 'cat-nature', word: 'Erosie',           hintEasy: 'Slijten',       hintMedium: 'Water',          hintHard: 'Geleidelijk' },
  { categoryId: 'cat-nature', word: 'Sediment',         hintEasy: 'Bezinksel',     hintMedium: 'Water',          hintHard: 'Lagen' },
  { categoryId: 'cat-nature', word: 'Grondwater',       hintEasy: 'Verborgen',     hintMedium: 'Diep',           hintHard: 'Spons' },
  { categoryId: 'cat-nature', word: 'Regenwoud',        hintEasy: 'Groen',         hintMedium: 'Regen',          hintHard: 'Longen' },
  { categoryId: 'cat-nature', word: 'Mantel',           hintEasy: 'Aarde',         hintMedium: 'Heet',           hintHard: 'Vloeibaar' },
  { categoryId: 'cat-nature', word: 'Aardkern',         hintEasy: 'Midden',        hintMedium: 'Heet',           hintHard: 'IJzer' },
  { categoryId: 'cat-nature', word: 'Tektonische plaat', hintEasy: 'Beweegt',     hintMedium: 'Aardbeving',     hintHard: 'Drijvend' },
  { categoryId: 'cat-nature', word: 'Riftspleet',       hintEasy: 'Scheur',        hintMedium: 'Aarde',          hintHard: 'Platen' },
  { categoryId: 'cat-nature', word: 'Koraalbleking',    hintEasy: 'Wit',           hintMedium: 'Zee',            hintHard: 'Temperatuur' },
  { categoryId: 'cat-nature', word: 'Zeeniveau',        hintEasy: 'Water',         hintMedium: 'Stijgen',        hintHard: 'Klimaat' },
  { categoryId: 'cat-nature', word: 'Zuurstof',         hintEasy: 'Ademen',        hintMedium: 'Bomen',          hintHard: 'Leven' },
  { categoryId: 'cat-nature', word: 'Koolstofkringloop', hintEasy: 'CO2',          hintMedium: 'Planten',        hintHard: 'Balans' },
  { categoryId: 'cat-nature', word: 'Fotosynthese',     hintEasy: 'Licht',         hintMedium: 'Plant',          hintHard: 'Omzetten' },
  { categoryId: 'cat-nature', word: 'Voedselketen',     hintEasy: 'Eten',          hintMedium: 'Dieren',         hintHard: 'Schakels' },
]
