import { PrismaClient } from '@prisma/client'
import { allExtraWords } from './seed-extra-all'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Create categories
  await Promise.all([
    prisma.category.upsert({ where: { id: 'cat-animals' }, update: {}, create: { id: 'cat-animals', name: 'Dieren', icon: '🐾', isDefault: true } }),
    prisma.category.upsert({ where: { id: 'cat-food' }, update: {}, create: { id: 'cat-food', name: 'Eten & Drinken', icon: '🍕', isDefault: true } }),
    prisma.category.upsert({ where: { id: 'cat-countries' }, update: {}, create: { id: 'cat-countries', name: 'Landen', icon: '🌍', isDefault: true } }),
    prisma.category.upsert({ where: { id: 'cat-sports' }, update: {}, create: { id: 'cat-sports', name: 'Sport', icon: '⚽', isDefault: true } }),
    prisma.category.upsert({ where: { id: 'cat-objects' }, update: {}, create: { id: 'cat-objects', name: 'Voorwerpen', icon: '🎁', isDefault: true } }),
    prisma.category.upsert({ where: { id: 'cat-jobs' }, update: {}, create: { id: 'cat-jobs', name: 'Beroepen', icon: '👷', isDefault: true } }),
    prisma.category.upsert({ where: { id: 'cat-music' }, update: {}, create: { id: 'cat-music', name: 'Muziek', icon: '🎵', isDefault: true } }),
    prisma.category.upsert({ where: { id: 'cat-nature' }, update: {}, create: { id: 'cat-nature', name: 'Natuur', icon: '🌿', isDefault: true } }),
  ])

  console.log('✅ Categories created')

  const words = [
    // ─── DIEREN (55) ────────────────────────────────────────────
    { categoryId: 'cat-animals', word: 'Olifant',    hintEasy: 'Slurf',       hintMedium: 'Afrika',       hintHard: 'Ivoor' },
    { categoryId: 'cat-animals', word: 'Kangoeroe',  hintEasy: 'Buidel',      hintMedium: 'Australië',    hintHard: 'Springen' },
    { categoryId: 'cat-animals', word: 'Pinguïn',    hintEasy: 'Wadelen',     hintMedium: 'Antarctica',   hintHard: 'Smoking' },
    { categoryId: 'cat-animals', word: 'Leeuw',      hintEasy: 'Manen',       hintMedium: 'Savanne',      hintHard: 'Koning' },
    { categoryId: 'cat-animals', word: 'Dolfijn',    hintEasy: 'Springen',    hintMedium: 'Zee',          hintHard: 'Sonar' },
    { categoryId: 'cat-animals', word: 'Giraffe',    hintEasy: 'Nek',         hintMedium: 'Vlekken',      hintHard: 'Hoogte' },
    { categoryId: 'cat-animals', word: 'Koe',        hintEasy: 'Melk',        hintMedium: 'Boerderij',    hintHard: 'Moe' },
    { categoryId: 'cat-animals', word: 'Hond',       hintEasy: 'Blaft',       hintMedium: 'Huisdier',     hintHard: 'Trouw' },
    { categoryId: 'cat-animals', word: 'Kat',        hintEasy: 'Miauw',       hintMedium: 'Krabben',      hintHard: 'Negen' },
    { categoryId: 'cat-animals', word: 'Konijn',     hintEasy: 'Oren',        hintMedium: 'Wortel',       hintHard: 'Huppelen' },
    { categoryId: 'cat-animals', word: 'Aap',        hintEasy: 'Banaan',      hintMedium: 'Jungle',       hintHard: 'Darwin' },
    { categoryId: 'cat-animals', word: 'Schildpad',  hintEasy: 'Schild',      hintMedium: 'Traag',        hintHard: 'Eeuwig' },
    { categoryId: 'cat-animals', word: 'Slang',      hintEasy: 'Gif',         hintMedium: 'Kronkelen',    hintHard: 'Eden' },
    { categoryId: 'cat-animals', word: 'Paard',      hintEasy: 'Galop',       hintMedium: 'Stal',         hintHard: 'Hoefijzer' },
    { categoryId: 'cat-animals', word: 'Varken',     hintEasy: 'Knor',        hintMedium: 'Modder',       hintHard: 'Spek' },
    { categoryId: 'cat-animals', word: 'Schaap',     hintEasy: 'Wol',         hintMedium: 'Weide',        hintHard: 'Scheren' },
    { categoryId: 'cat-animals', word: 'Eend',       hintEasy: 'Kwaken',      hintMedium: 'Vijver',       hintHard: 'Brood' },
    { categoryId: 'cat-animals', word: 'Uil',        hintEasy: 'Ogen',        hintMedium: 'Nacht',        hintHard: 'Wijs' },
    { categoryId: 'cat-animals', word: 'Vos',        hintEasy: 'Rood',        hintMedium: 'Sluw',         hintHard: 'Kip' },
    { categoryId: 'cat-animals', word: 'Wolf',       hintEasy: 'Huilen',      hintMedium: 'Roedel',       hintHard: 'Roodkapje' },
    { categoryId: 'cat-animals', word: 'Beer',       hintEasy: 'Honing',      hintMedium: 'Winterslaap',  hintHard: 'Pels' },
    { categoryId: 'cat-animals', word: 'Krokodil',   hintEasy: 'Tanden',      hintMedium: 'Rivier',       hintHard: 'Tranen' },
    { categoryId: 'cat-animals', word: 'Neushoorn',  hintEasy: 'Hoorn',       hintMedium: 'Safari',       hintHard: 'Pantser' },
    { categoryId: 'cat-animals', word: 'Zebra',      hintEasy: 'Strepen',     hintMedium: 'Savanne',      hintHard: 'Oversteek' },
    { categoryId: 'cat-animals', word: 'Flamingo',   hintEasy: 'Roze',        hintMedium: 'Poot',         hintHard: 'Zout' },
    { categoryId: 'cat-animals', word: 'Kameel',     hintEasy: 'Bult',        hintMedium: 'Woestijn',     hintHard: 'Dorst' },
    { categoryId: 'cat-animals', word: 'Octopus',    hintEasy: 'Tentakels',   hintMedium: 'Acht',         hintHard: 'Inkt' },
    { categoryId: 'cat-animals', word: 'Haai',       hintEasy: 'Vin',         hintMedium: 'Oceaan',       hintHard: 'Aanval' },
    { categoryId: 'cat-animals', word: 'Papegaai',   hintEasy: 'Napraten',    hintMedium: 'Tropisch',     hintHard: 'Piraat' },
    { categoryId: 'cat-animals', word: 'Gorilla',    hintEasy: 'Sterk',       hintMedium: 'Jungle',       hintHard: 'Congolees' },
    { categoryId: 'cat-animals', word: 'Tijger',     hintEasy: 'Strepen',     hintMedium: 'Bengalen',     hintHard: 'Kracht' },
    { categoryId: 'cat-animals', word: 'Luipaard',   hintEasy: 'Vlekken',     hintMedium: 'Boom',         hintHard: 'Snel' },
    { categoryId: 'cat-animals', word: 'Koala',      hintEasy: 'Eucalyptus',  hintMedium: 'Australië',    hintHard: 'Knuffelen' },
    { categoryId: 'cat-animals', word: 'Panda',      hintEasy: 'Bamboe',      hintMedium: 'China',        hintHard: 'Zeldzaam' },
    { categoryId: 'cat-animals', word: 'Muis',       hintEasy: 'Kaas',        hintMedium: 'Knaagdier',    hintHard: 'Piepen' },
    { categoryId: 'cat-animals', word: 'Hamster',    hintEasy: 'Wangen',      hintMedium: 'Kooi',         hintHard: 'Rennen' },
    { categoryId: 'cat-animals', word: 'Spin',       hintEasy: 'Web',         hintMedium: 'Acht',         hintHard: 'Angst' },
    { categoryId: 'cat-animals', word: 'Bij',        hintEasy: 'Honing',      hintMedium: 'Bloem',        hintHard: 'Steek' },
    { categoryId: 'cat-animals', word: 'Vlinder',    hintEasy: 'Vleugels',    hintMedium: 'Bloem',        hintHard: 'Cocon' },
    { categoryId: 'cat-animals', word: 'Eekhoorn',   hintEasy: 'Noten',       hintMedium: 'Boom',         hintHard: 'Winter' },
    { categoryId: 'cat-animals', word: 'Egel',       hintEasy: 'Stekels',     hintMedium: 'Tuin',         hintHard: 'Rollen' },
    { categoryId: 'cat-animals', word: 'Ooievaar',   hintEasy: 'Baby',        hintMedium: 'Nest',         hintHard: 'Holland' },
    { categoryId: 'cat-animals', word: 'Bever',      hintEasy: 'Dam',         hintMedium: 'Rivier',       hintHard: 'Hout' },
    { categoryId: 'cat-animals', word: 'Walvis',     hintEasy: 'Spuitgat',    hintMedium: 'Oceaan',       hintHard: 'Zingen' },
    { categoryId: 'cat-animals', word: 'Zeehond',    hintEasy: 'Flippers',    hintMedium: 'Strand',       hintHard: 'Bal' },
    { categoryId: 'cat-animals', word: 'Hert',       hintEasy: 'Gewei',       hintMedium: 'Bos',          hintHard: 'Bambi' },
    { categoryId: 'cat-animals', word: 'Ezel',       hintEasy: 'Balken',      hintMedium: 'Boerderij',    hintHard: 'Koppig' },
    { categoryId: 'cat-animals', word: 'Lama',       hintEasy: 'Spugen',      hintMedium: 'Andes',        hintHard: 'Alpaca' },
    { categoryId: 'cat-animals', word: 'Otter',      hintEasy: 'Rivier',      hintMedium: 'Zwemmen',      hintHard: 'Handen' },
    { categoryId: 'cat-animals', word: 'Nijlpaard',  hintEasy: 'Water',       hintMedium: 'Nijl',         hintHard: 'Gevaarlijk' },
    { categoryId: 'cat-animals', word: 'Kwal',       hintEasy: 'Tentakels',   hintMedium: 'Zee',          hintHard: 'Branden' },
    { categoryId: 'cat-animals', word: 'Kreeft',     hintEasy: 'Scharen',     hintMedium: 'Zee',          hintHard: 'Rood' },
    { categoryId: 'cat-animals', word: 'Kikker',     hintEasy: 'Kwaken',      hintMedium: 'Vijver',       hintHard: 'Sprong' },
    { categoryId: 'cat-animals', word: 'Libel',      hintEasy: 'Vleugels',    hintMedium: 'Water',        hintHard: 'Helikopter' },
    { categoryId: 'cat-animals', word: 'Gibbel',     hintEasy: 'Vin',         hintMedium: 'Rivier',       hintHard: 'Stilte' },
    { categoryId: 'cat-animals', word: 'Neusaap',    hintEasy: 'Neus',        hintMedium: 'Borneo',       hintHard: 'Rood' },

    // ─── ETEN & DRINKEN (55) ────────────────────────────────────
    { categoryId: 'cat-food', word: 'Pizza',         hintEasy: 'Tomaat',      hintMedium: 'Italië',       hintHard: 'Napels' },
    { categoryId: 'cat-food', word: 'Hamburger',     hintEasy: 'Gehakt',      hintMedium: 'Amerika',      hintHard: 'Fastfood' },
    { categoryId: 'cat-food', word: 'Spaghetti',     hintEasy: 'Pasta',       hintMedium: 'Bolognese',    hintHard: 'Slurpen' },
    { categoryId: 'cat-food', word: 'Pannenkoek',    hintEasy: 'Stroop',      hintMedium: 'Beslag',       hintHard: 'Draaien' },
    { categoryId: 'cat-food', word: 'Friet',         hintEasy: 'Aardappel',   hintMedium: 'Mayonaise',    hintHard: 'België' },
    { categoryId: 'cat-food', word: 'Chocolade',     hintEasy: 'Cacao',       hintMedium: 'Zoet',         hintHard: 'Belg' },
    { categoryId: 'cat-food', word: 'IJs',           hintEasy: 'Koud',        hintMedium: 'Zomer',        hintHard: 'Schepje' },
    { categoryId: 'cat-food', word: 'Brood',         hintEasy: 'Tarwe',       hintMedium: 'Bakker',       hintHard: 'Graan' },
    { categoryId: 'cat-food', word: 'Kaas',          hintEasy: 'Melk',        hintMedium: 'Holland',      hintHard: 'Gaten' },
    { categoryId: 'cat-food', word: 'Banaan',        hintEasy: 'Geel',        hintMedium: 'Tropisch',     hintHard: 'Aap' },
    { categoryId: 'cat-food', word: 'Tomaat',        hintEasy: 'Rood',        hintMedium: 'Tuin',         hintHard: 'Ketchup' },
    { categoryId: 'cat-food', word: 'Aardappel',     hintEasy: 'Knol',        hintMedium: 'Boer',         hintHard: 'Iers' },
    { categoryId: 'cat-food', word: 'Sushi',         hintEasy: 'Rijst',       hintMedium: 'Japan',        hintHard: 'Eetstokjes' },
    { categoryId: 'cat-food', word: 'Soep',          hintEasy: 'Warm',        hintMedium: 'Lepel',        hintHard: 'Ziek' },
    { categoryId: 'cat-food', word: 'Ei',            hintEasy: 'Kip',         hintMedium: 'Ontbijt',      hintHard: 'Pasen' },
    { categoryId: 'cat-food', word: 'Melk',          hintEasy: 'Koe',         hintMedium: 'Wit',          hintHard: 'Calcium' },
    { categoryId: 'cat-food', word: 'Koffie',        hintEasy: 'Cafeïne',     hintMedium: 'Bonen',        hintHard: 'Wakker' },
    { categoryId: 'cat-food', word: 'Thee',          hintEasy: 'Blad',        hintMedium: 'Warm',         hintHard: 'Engeland' },
    { categoryId: 'cat-food', word: 'Sinaasappel',   hintEasy: 'Oranje',      hintMedium: 'Tropisch',     hintHard: 'Vitamine' },
    { categoryId: 'cat-food', word: 'Aardbei',       hintEasy: 'Rood',        hintMedium: 'Zomer',        hintHard: 'Jam' },
    { categoryId: 'cat-food', word: 'Druif',         hintEasy: 'Wijn',        hintMedium: 'Tros',         hintHard: 'Oogst' },
    { categoryId: 'cat-food', word: 'Citroen',       hintEasy: 'Zuur',        hintMedium: 'Geel',         hintHard: 'Limonade' },
    { categoryId: 'cat-food', word: 'Koekje',        hintEasy: 'Zoet',        hintMedium: 'Knapperig',    hintHard: 'Oma' },
    { categoryId: 'cat-food', word: 'Taart',         hintEasy: 'Kaarsje',     hintMedium: 'Verjaardag',   hintHard: 'Bakken' },
    { categoryId: 'cat-food', word: 'Yoghurt',       hintEasy: 'Zuur',        hintMedium: 'Melk',         hintHard: 'Gezond' },
    { categoryId: 'cat-food', word: 'Rijst',         hintEasy: 'Korrel',      hintMedium: 'Azië',         hintHard: 'Pap' },
    { categoryId: 'cat-food', word: 'Chips',         hintEasy: 'Knapperig',   hintMedium: 'Zout',         hintHard: 'Zakje' },
    { categoryId: 'cat-food', word: 'Popcorn',       hintEasy: 'Maïs',        hintMedium: 'Bioscoop',     hintHard: 'Knal' },
    { categoryId: 'cat-food', word: 'Worst',         hintEasy: 'Vlees',       hintMedium: 'Rook',         hintHard: 'Slager' },
    { categoryId: 'cat-food', word: 'Croissant',     hintEasy: 'Boter',       hintMedium: 'Frans',        hintHard: 'Ontbijt' },
    { categoryId: 'cat-food', word: 'Haring',        hintEasy: 'Vis',         hintMedium: 'Holland',      hintHard: 'Uitjes' },
    { categoryId: 'cat-food', word: 'Drop',          hintEasy: 'Zoethout',    hintMedium: 'Zwart',        hintHard: 'Hollands' },
    { categoryId: 'cat-food', word: 'Stroopwafel',   hintEasy: 'Stroop',      hintMedium: 'Wafel',        hintHard: 'Gouda' },
    { categoryId: 'cat-food', word: 'Pindakaas',     hintEasy: 'Pinda',       hintMedium: 'Smeersel',     hintHard: 'Amerika' },
    { categoryId: 'cat-food', word: 'Honing',        hintEasy: 'Bij',         hintMedium: 'Zoet',         hintHard: 'Bijenkorf' },
    { categoryId: 'cat-food', word: 'Bier',          hintEasy: 'Hop',         hintMedium: 'Glas',         hintHard: 'Proost' },
    { categoryId: 'cat-food', word: 'Wijn',          hintEasy: 'Druif',       hintMedium: 'Kurk',         hintHard: 'Bordeaux' },
    { categoryId: 'cat-food', word: 'Cola',          hintEasy: 'Suiker',      hintMedium: 'Frisdrank',    hintHard: 'Amerika' },
    { categoryId: 'cat-food', word: 'Meloen',        hintEasy: 'Groen',       hintMedium: 'Zomer',        hintHard: 'Zaden' },
    { categoryId: 'cat-food', word: 'Komkommer',     hintEasy: 'Groen',       hintMedium: 'Salade',       hintHard: 'Fris' },
    { categoryId: 'cat-food', word: 'Broccoli',      hintEasy: 'Groen',       hintMedium: 'Gezond',       hintHard: 'Boom' },
    { categoryId: 'cat-food', word: 'Paprika',       hintEasy: 'Kleur',       hintMedium: 'Groente',      hintHard: 'Spanje' },
    { categoryId: 'cat-food', word: 'Ui',            hintEasy: 'Tranen',      hintMedium: 'Bouillon',     hintHard: 'Lagen' },
    { categoryId: 'cat-food', word: 'Knoflook',      hintEasy: 'Scherp',      hintMedium: 'Bol',          hintHard: 'Vampier' },
    { categoryId: 'cat-food', word: 'Olijfolie',     hintEasy: 'Olijf',       hintMedium: 'Bakken',       hintHard: 'Mediterraan' },
    { categoryId: 'cat-food', word: 'Zalm',          hintEasy: 'Roze',        hintMedium: 'Vis',          hintHard: 'Noorwegen' },
    { categoryId: 'cat-food', word: 'Appel',         hintEasy: 'Rood',        hintMedium: 'Boom',         hintHard: 'Eva' },
    { categoryId: 'cat-food', word: 'Peer',          hintEasy: 'Groen',       hintMedium: 'Boom',         hintHard: 'Lampje' },
    { categoryId: 'cat-food', word: 'Mango',         hintEasy: 'Tropisch',    hintMedium: 'Geel',         hintHard: 'Azië' },
    { categoryId: 'cat-food', word: 'Ananas',        hintEasy: 'Tropisch',    hintMedium: 'Stekelig',     hintHard: 'Hawaii' },
    { categoryId: 'cat-food', word: 'Kiwi',          hintEasy: 'Groen',       hintMedium: 'Harig',        hintHard: 'Nieuw-Zeeland' },
    { categoryId: 'cat-food', word: 'Watermeloen',   hintEasy: 'Rood',        hintMedium: 'Zomer',        hintHard: 'Pitten' },
    { categoryId: 'cat-food', word: 'Kersenijs',     hintEasy: 'Kersen',      hintMedium: 'Zoet',         hintHard: 'Zomer' },
    { categoryId: 'cat-food', word: 'Baguette',      hintEasy: 'Brood',       hintMedium: 'Knapperig',    hintHard: 'Fiets' },
    { categoryId: 'cat-food', word: 'Kauwgom',       hintEasy: 'Kauwen',      hintMedium: 'Zoet',         hintHard: 'Blaas' },
    { categoryId: 'cat-food', word: 'Wafels',        hintEasy: 'Belg',        hintMedium: 'Beslag',       hintHard: 'Raster' },

    // ─── LANDEN (50) ────────────────────────────────────────────
    { categoryId: 'cat-countries', word: 'Nederland',     hintEasy: 'Tulpen',     hintMedium: 'Polders',      hintHard: 'Oranje' },
    { categoryId: 'cat-countries', word: 'Frankrijk',     hintEasy: 'Eiffeltoren',hintMedium: 'Wijn',         hintHard: 'Liefde' },
    { categoryId: 'cat-countries', word: 'Italië',        hintEasy: 'Pizza',      hintMedium: 'Laarzen',      hintHard: 'Colosseum' },
    { categoryId: 'cat-countries', word: 'Spanje',        hintEasy: 'Flamenco',   hintMedium: 'Stieren',      hintHard: 'Siësta' },
    { categoryId: 'cat-countries', word: 'Japan',         hintEasy: 'Sushi',      hintMedium: 'Fuji',         hintHard: 'Sakura' },
    { categoryId: 'cat-countries', word: 'Egypte',        hintEasy: 'Piramides',  hintMedium: 'Nijl',         hintHard: 'Farao' },
    { categoryId: 'cat-countries', word: 'Brazilië',      hintEasy: 'Carnaval',   hintMedium: 'Jungle',       hintHard: 'Samba' },
    { categoryId: 'cat-countries', word: 'Australië',     hintEasy: 'Kangoeroe',  hintMedium: 'Outback',      hintHard: 'Sydney' },
    { categoryId: 'cat-countries', word: 'China',         hintEasy: 'Muur',       hintMedium: 'Thee',         hintHard: 'Draken' },
    { categoryId: 'cat-countries', word: 'India',         hintEasy: 'Curry',      hintMedium: 'Ganges',       hintHard: 'Sari' },
    { categoryId: 'cat-countries', word: 'Duitsland',     hintEasy: 'Bier',       hintMedium: 'Autobahn',     hintHard: 'Bratwurst' },
    { categoryId: 'cat-countries', word: 'Rusland',       hintEasy: 'Wodka',      hintMedium: 'Sneeuw',       hintHard: 'Tsar' },
    { categoryId: 'cat-countries', word: 'Amerika',       hintEasy: 'Hamburger',  hintMedium: 'Vrijheid',     hintHard: 'Hollywood' },
    { categoryId: 'cat-countries', word: 'Canada',        hintEasy: 'Esdoorn',    hintMedium: 'Hockey',       hintHard: 'Bever' },
    { categoryId: 'cat-countries', word: 'Mexico',        hintEasy: 'Taco',       hintMedium: 'Sombrero',     hintHard: 'Mariachi' },
    { categoryId: 'cat-countries', word: 'Griekenland',   hintEasy: 'Olijf',      hintMedium: 'Parthenon',    hintHard: 'Filosofie' },
    { categoryId: 'cat-countries', word: 'Noorwegen',     hintEasy: 'Fjorden',    hintMedium: 'Zalm',         hintHard: 'Vikings' },
    { categoryId: 'cat-countries', word: 'Zweden',        hintEasy: 'IKEA',       hintMedium: 'Sneeuw',       hintHard: 'Nobel' },
    { categoryId: 'cat-countries', word: 'Portugal',      hintEasy: 'Fado',       hintMedium: 'Surfen',       hintHard: 'Ontdekkers' },
    { categoryId: 'cat-countries', word: 'België',        hintEasy: 'Chocolade',  hintMedium: 'Wafels',       hintHard: 'Manneken' },
    { categoryId: 'cat-countries', word: 'Zwitserland',   hintEasy: 'Kaas',       hintMedium: 'Bergen',       hintHard: 'Neutraal' },
    { categoryId: 'cat-countries', word: 'Turkije',       hintEasy: 'Kebab',      hintMedium: 'Brug',         hintHard: 'Sultaan' },
    { categoryId: 'cat-countries', word: 'Marokko',       hintEasy: 'Tajine',     hintMedium: 'Sahara',       hintHard: 'Souk' },
    { categoryId: 'cat-countries', word: 'Polen',         hintEasy: 'Pierogi',    hintMedium: 'Oost',         hintHard: 'Chopin' },
    { categoryId: 'cat-countries', word: 'Ierland',       hintEasy: 'Klaver',     hintMedium: 'Guinness',     hintHard: 'Leprechaun' },
    { categoryId: 'cat-countries', word: 'Schotland',     hintEasy: 'Whisky',     hintMedium: 'Highland',     hintHard: 'Doedelzak' },
    { categoryId: 'cat-countries', word: 'Engeland',      hintEasy: 'Thee',       hintMedium: 'Koningin',     hintHard: 'Cricket' },
    { categoryId: 'cat-countries', word: 'Argentinië',    hintEasy: 'Tango',      hintMedium: 'Voetbal',      hintHard: 'Pampas' },
    { categoryId: 'cat-countries', word: 'Kenia',         hintEasy: 'Safari',     hintMedium: 'Marathon',     hintHard: 'Masai' },
    { categoryId: 'cat-countries', word: 'Indonesië',     hintEasy: 'Rijst',      hintMedium: 'Eilanden',     hintHard: 'Batik' },
    { categoryId: 'cat-countries', word: 'Thailand',      hintEasy: 'Tempel',     hintMedium: 'Rijst',        hintHard: 'Olifant' },
    { categoryId: 'cat-countries', word: 'Cuba',          hintEasy: 'Sigaar',     hintMedium: 'Rum',          hintHard: 'Revolutie' },
    { categoryId: 'cat-countries', word: 'Vietnam',       hintEasy: 'Pho',        hintMedium: 'Rijstveld',    hintHard: 'Bamboe' },
    { categoryId: 'cat-countries', word: 'Denemarken',    hintEasy: 'Lego',       hintMedium: 'Viking',       hintHard: 'Hygge' },
    { categoryId: 'cat-countries', word: 'Finland',       hintEasy: 'Sauna',      hintMedium: 'Sneeuw',       hintHard: 'Nokia' },
    { categoryId: 'cat-countries', word: 'Oostenrijk',    hintEasy: 'Mozart',     hintMedium: 'Bergen',       hintHard: 'Habsburg' },
    { categoryId: 'cat-countries', word: 'IJsland',       hintEasy: 'Geisers',    hintMedium: 'Vulkaan',      hintHard: 'Aurora' },
    { categoryId: 'cat-countries', word: 'Peru',          hintEasy: 'Inca',       hintMedium: 'Lama',         hintHard: 'Quinoa' },
    { categoryId: 'cat-countries', word: 'Colombia',      hintEasy: 'Koffie',     hintMedium: 'Caribisch',    hintHard: 'Orchidee' },
    { categoryId: 'cat-countries', word: 'Nigeria',       hintEasy: 'Lagos',      hintMedium: 'Olie',         hintHard: 'Nollywood' },
    { categoryId: 'cat-countries', word: 'Ghana',         hintEasy: 'Cacao',      hintMedium: 'Goud',         hintHard: 'Ashanti' },
    { categoryId: 'cat-countries', word: 'Pakistan',      hintEasy: 'Islamabad',  hintMedium: 'Islam',        hintHard: 'Himalaya' },
    { categoryId: 'cat-countries', word: 'Chili',         hintEasy: 'Andes',      hintMedium: 'Koper',        hintHard: 'Peper' },
    { categoryId: 'cat-countries', word: 'Nieuw-Zeeland', hintEasy: 'Schapen',    hintMedium: 'Rugby',        hintHard: 'Hobbit' },
    { categoryId: 'cat-countries', word: 'Ethiopië',      hintEasy: 'Koffie',     hintMedium: 'Droogte',      hintHard: 'Marathon' },
    { categoryId: 'cat-countries', word: 'Kroatië',       hintEasy: 'Zee',        hintMedium: 'Eilanden',     hintHard: 'Dalmatisch' },
    { categoryId: 'cat-countries', word: 'Hongarije',     hintEasy: 'Goulash',    hintMedium: 'Donau',        hintHard: 'Puszta' },
    { categoryId: 'cat-countries', word: 'Kazachstan',    hintEasy: 'Steppe',     hintMedium: 'Olie',         hintHard: 'Nomaden' },
    { categoryId: 'cat-countries', word: 'Zweden',        hintEasy: 'ABBA',       hintMedium: 'Ikea',         hintHard: 'Midsommar' },
    { categoryId: 'cat-countries', word: 'Israël',        hintEasy: 'Jeruzalem',  hintMedium: 'Woestijn',     hintHard: 'Sjabbat' },

    // ─── SPORT (50) ─────────────────────────────────────────────
    { categoryId: 'cat-sports', word: 'Voetbal',      hintEasy: 'Goal',        hintMedium: 'Veld',         hintHard: 'WK' },
    { categoryId: 'cat-sports', word: 'Tennis',       hintEasy: 'Racket',      hintMedium: 'Net',          hintHard: 'Wimbledon' },
    { categoryId: 'cat-sports', word: 'Zwemmen',      hintEasy: 'Water',       hintMedium: 'Banen',        hintHard: 'Crawl' },
    { categoryId: 'cat-sports', word: 'Basketbal',    hintEasy: 'Ring',        hintMedium: 'Parket',       hintHard: 'NBA' },
    { categoryId: 'cat-sports', word: 'Schaatsen',    hintEasy: 'Ijs',         hintMedium: 'Klapschaats',  hintHard: 'Elfstedentocht' },
    { categoryId: 'cat-sports', word: 'Wielrennen',   hintEasy: 'Fiets',       hintMedium: 'Ketting',      hintHard: 'Tour' },
    { categoryId: 'cat-sports', word: 'Skiën',        hintEasy: 'Sneeuw',      hintMedium: 'Piste',        hintHard: 'Slalom' },
    { categoryId: 'cat-sports', word: 'Roeien',       hintEasy: 'Peddel',      hintMedium: 'Rivier',       hintHard: 'Scull' },
    { categoryId: 'cat-sports', word: 'Boksen',       hintEasy: 'Handschoenen',hintMedium: 'Ring',         hintHard: 'Knock-out' },
    { categoryId: 'cat-sports', word: 'Judo',         hintEasy: 'Gooi',        hintMedium: 'Mat',          hintHard: 'Japans' },
    { categoryId: 'cat-sports', word: 'Turnen',       hintEasy: 'Balk',        hintMedium: 'Salto',        hintHard: 'Elegantie' },
    { categoryId: 'cat-sports', word: 'Volleybal',    hintEasy: 'Net',         hintMedium: 'Strand',       hintHard: 'Spike' },
    { categoryId: 'cat-sports', word: 'Handbal',      hintEasy: 'Doel',        hintMedium: 'Gooien',       hintHard: 'Aanval' },
    { categoryId: 'cat-sports', word: 'Rugby',        hintEasy: 'Ovaal',       hintMedium: 'Tackle',       hintHard: 'Scrum' },
    { categoryId: 'cat-sports', word: 'Golf',         hintEasy: 'Club',        hintMedium: 'Gat',          hintHard: 'Caddie' },
    { categoryId: 'cat-sports', word: 'Baseball',     hintEasy: 'Slagstok',    hintMedium: 'Honk',         hintHard: 'Homerun' },
    { categoryId: 'cat-sports', word: 'Tafeltennis',  hintEasy: 'Pingpong',    hintMedium: 'Tafel',        hintHard: 'Spin' },
    { categoryId: 'cat-sports', word: 'Badminton',    hintEasy: 'Shuttle',     hintMedium: 'Racket',       hintHard: 'Veer' },
    { categoryId: 'cat-sports', word: 'Schermen',     hintEasy: 'Degen',       hintMedium: 'Masker',       hintHard: 'Touché' },
    { categoryId: 'cat-sports', word: 'Paardrijden',  hintEasy: 'Zadel',       hintMedium: 'Paard',        hintHard: 'Dresuur' },
    { categoryId: 'cat-sports', word: 'Klimmen',      hintEasy: 'Rots',        hintMedium: 'Touw',         hintHard: 'Hoogte' },
    { categoryId: 'cat-sports', word: 'Surfen',       hintEasy: 'Golf',        hintMedium: 'Strand',       hintHard: 'Wipeout' },
    { categoryId: 'cat-sports', word: 'Snowboarden',  hintEasy: 'Sneeuw',      hintMedium: 'Piste',        hintHard: 'Halfpipe' },
    { categoryId: 'cat-sports', word: 'Boogschieten', hintEasy: 'Pijl',        hintMedium: 'Doel',         hintHard: 'Robin' },
    { categoryId: 'cat-sports', word: 'IJshockey',    hintEasy: 'Puck',        hintMedium: 'Ijs',          hintHard: 'Check' },
    { categoryId: 'cat-sports', word: 'Cricket',      hintEasy: 'Slagstok',    hintMedium: 'Wicket',       hintHard: 'Engeland' },
    { categoryId: 'cat-sports', word: 'Atletiek',     hintEasy: 'Hardlopen',   hintMedium: 'Stadion',      hintHard: 'Spikes' },
    { categoryId: 'cat-sports', word: 'Marathon',     hintEasy: 'Hardlopen',   hintMedium: 'Afstand',      hintHard: 'Athene' },
    { categoryId: 'cat-sports', word: 'Triathlon',    hintEasy: 'Drie',        hintMedium: 'Combinatie',   hintHard: 'Uithouding' },
    { categoryId: 'cat-sports', word: 'Bowling',      hintEasy: 'Pins',        hintMedium: 'Bal',          hintHard: 'Strike' },
    { categoryId: 'cat-sports', word: 'Darten',       hintEasy: 'Pijl',        hintMedium: 'Klok',         hintHard: 'Bull' },
    { categoryId: 'cat-sports', word: 'Biljart',      hintEasy: 'Queue',       hintMedium: 'Bal',          hintHard: 'Drieband' },
    { categoryId: 'cat-sports', word: 'Schaken',      hintEasy: 'Pion',        hintMedium: 'Schaakbord',   hintHard: 'Strategie' },
    { categoryId: 'cat-sports', word: 'Waterpolo',    hintEasy: 'Doel',        hintMedium: 'Zwemmen',      hintHard: 'Polo' },
    { categoryId: 'cat-sports', word: 'Karate',       hintEasy: 'Kata',        hintMedium: 'Japan',        hintHard: 'Band' },
    { categoryId: 'cat-sports', word: 'Taekwondo',    hintEasy: 'Trap',        hintMedium: 'Korea',        hintHard: 'Gordel' },
    { categoryId: 'cat-sports', word: 'Worstelen',    hintEasy: 'Kracht',      hintMedium: 'Mat',          hintHard: 'Greep' },
    { categoryId: 'cat-sports', word: 'Hockey',       hintEasy: 'Stick',       hintMedium: 'Veld',         hintHard: 'Oranje' },
    { categoryId: 'cat-sports', word: 'Lacrosse',     hintEasy: 'Net',         hintMedium: 'Stok',         hintHard: 'Canada' },
    { categoryId: 'cat-sports', word: 'Zeilen',       hintEasy: 'Mast',        hintMedium: 'Wind',         hintHard: 'Regatta' },
    { categoryId: 'cat-sports', word: 'Kanoën',       hintEasy: 'Peddel',      hintMedium: 'Rivier',       hintHard: 'Stroming' },
    { categoryId: 'cat-sports', word: 'Parachutespringen', hintEasy: 'Valscherm', hintMedium: 'Lucht', hintHard: 'Vrije val' },
    { categoryId: 'cat-sports', word: 'Freerunning',  hintEasy: 'Springen',    hintMedium: 'Stad',         hintHard: 'Parkour' },
    { categoryId: 'cat-sports', word: 'Sumo',         hintEasy: 'Zwaar',       hintMedium: 'Japan',        hintHard: 'Ring' },
    { categoryId: 'cat-sports', word: 'Schietsport',  hintEasy: 'Doel',        hintMedium: 'Pistool',      hintHard: 'Roos' },
    { categoryId: 'cat-sports', word: 'Schoonspringen',hintEasy: 'Plank',      hintMedium: 'Water',        hintHard: 'Duiken' },
    { categoryId: 'cat-sports', word: 'Langlaufen',   hintEasy: 'Ski',         hintMedium: 'Sneeuw',       hintHard: 'Noorwegen' },
    { categoryId: 'cat-sports', word: 'Squash',       hintEasy: 'Racket',      hintMedium: 'Muur',         hintHard: 'Snelheid' },
    { categoryId: 'cat-sports', word: 'Fietscross',   hintEasy: 'BMX',         hintMedium: 'Modder',       hintHard: 'Sprong' },
    { categoryId: 'cat-sports', word: 'Joggen',       hintEasy: 'Hardlopen',   hintMedium: 'Park',         hintHard: 'Gezond' },

    // ─── VOORWERPEN (55) ────────────────────────────────────────
    { categoryId: 'cat-objects', word: 'Telefoon',     hintEasy: 'Bellen',     hintMedium: 'Scherm',       hintHard: 'Bereikbaar' },
    { categoryId: 'cat-objects', word: 'Paraplu',      hintEasy: 'Regen',      hintMedium: 'Bescherming',  hintHard: 'Droog' },
    { categoryId: 'cat-objects', word: 'Fiets',        hintEasy: 'Pedalen',    hintMedium: 'Holland',      hintHard: 'Vrijheid' },
    { categoryId: 'cat-objects', word: 'Sleutel',      hintEasy: 'Slot',       hintMedium: 'Metaal',       hintHard: 'Toegang' },
    { categoryId: 'cat-objects', word: 'Bril',         hintEasy: 'Glazen',     hintMedium: 'Ogen',         hintHard: 'Scherpte' },
    { categoryId: 'cat-objects', word: 'Tandenborstel',hintEasy: 'Tanden',     hintMedium: 'Badkamer',     hintHard: 'Tandpasta' },
    { categoryId: 'cat-objects', word: 'Lamp',         hintEasy: 'Licht',      hintMedium: 'Peertje',      hintHard: 'Idee' },
    { categoryId: 'cat-objects', word: 'Koelkast',     hintEasy: 'Koud',       hintMedium: 'Keuken',       hintHard: 'Bewaren' },
    { categoryId: 'cat-objects', word: 'Computer',     hintEasy: 'Scherm',     hintMedium: 'Internet',     hintHard: 'Code' },
    { categoryId: 'cat-objects', word: 'Boek',         hintEasy: 'Lezen',      hintMedium: 'Pagina',       hintHard: 'Kennis' },
    { categoryId: 'cat-objects', word: 'Pen',          hintEasy: 'Schrijven',  hintMedium: 'Inkt',         hintHard: 'Woord' },
    { categoryId: 'cat-objects', word: 'Klok',         hintEasy: 'Wijzers',    hintMedium: 'Tijd',         hintHard: 'Tikken' },
    { categoryId: 'cat-objects', word: 'Tafel',        hintEasy: 'Stoelen',    hintMedium: 'Eten',         hintHard: 'Oppervlak' },
    { categoryId: 'cat-objects', word: 'Stoel',        hintEasy: 'Zitten',     hintMedium: 'Poten',        hintHard: 'Rust' },
    { categoryId: 'cat-objects', word: 'Schaar',       hintEasy: 'Knippen',    hintMedium: 'Metaal',       hintHard: 'Blad' },
    { categoryId: 'cat-objects', word: 'Hamer',        hintEasy: 'Spijker',    hintMedium: 'Slaan',        hintHard: 'Timmeren' },
    { categoryId: 'cat-objects', word: 'Camera',       hintEasy: 'Foto',       hintMedium: 'Lens',         hintHard: 'Herinnering' },
    { categoryId: 'cat-objects', word: 'Gitaar',       hintEasy: 'Snaren',     hintMedium: 'Muziek',       hintHard: 'Rock' },
    { categoryId: 'cat-objects', word: 'Kaars',        hintEasy: 'Vlam',       hintMedium: 'Licht',        hintHard: 'Romantisch' },
    { categoryId: 'cat-objects', word: 'Spiegel',      hintEasy: 'Reflectie',  hintMedium: 'Glas',         hintHard: 'Zelf' },
    { categoryId: 'cat-objects', word: 'Koffer',       hintEasy: 'Reizen',     hintMedium: 'Kleding',      hintHard: 'Afscheid' },
    { categoryId: 'cat-objects', word: 'Rugzak',       hintEasy: 'Ruggen',     hintMedium: 'School',       hintHard: 'Riem' },
    { categoryId: 'cat-objects', word: 'Ballon',       hintEasy: 'Lucht',      hintMedium: 'Feest',        hintHard: 'Drijven' },
    { categoryId: 'cat-objects', word: 'Kompas',       hintEasy: 'Richting',   hintMedium: 'Noorden',      hintHard: 'Navigeren' },
    { categoryId: 'cat-objects', word: 'Microscoop',   hintEasy: 'Vergroten',  hintMedium: 'Wetenschap',   hintHard: 'Klein' },
    { categoryId: 'cat-objects', word: 'Telescoop',    hintEasy: 'Sterren',    hintMedium: 'Kijker',       hintHard: 'Ruimte' },
    { categoryId: 'cat-objects', word: 'Horloge',      hintEasy: 'Pols',       hintMedium: 'Tijd',         hintHard: 'Luxe' },
    { categoryId: 'cat-objects', word: 'Magneet',      hintEasy: 'Ijzer',      hintMedium: 'Aantrekken',   hintHard: 'Pool' },
    { categoryId: 'cat-objects', word: 'Zaklamp',      hintEasy: 'Licht',      hintMedium: 'Donker',       hintHard: 'Batterij' },
    { categoryId: 'cat-objects', word: 'Ladder',       hintEasy: 'Klimmen',    hintMedium: 'Sporten',      hintHard: 'Hoogte' },
    { categoryId: 'cat-objects', word: 'Emmer',        hintEasy: 'Water',      hintMedium: 'Schoonmaken',  hintHard: 'Vullen' },
    { categoryId: 'cat-objects', word: 'Bezem',        hintEasy: 'Vegen',      hintMedium: 'Schoonmaken',  hintHard: 'Heks' },
    { categoryId: 'cat-objects', word: 'Kurk',         hintEasy: 'Wijn',       hintMedium: 'Fles',         hintHard: 'Drijven' },
    { categoryId: 'cat-objects', word: 'Touw',         hintEasy: 'Knoop',      hintMedium: 'Klimmen',      hintHard: 'Verbinden' },
    { categoryId: 'cat-objects', word: 'Thermometer',  hintEasy: 'Temperatuur',hintMedium: 'Koorts',       hintHard: 'Kwik' },
    { categoryId: 'cat-objects', word: 'Wekker',       hintEasy: 'Slapen',     hintMedium: 'Ochtend',      hintHard: 'Rinkelen' },
    { categoryId: 'cat-objects', word: 'Woordenboek',  hintEasy: 'Woorden',    hintMedium: 'Taal',         hintHard: 'Definitie' },
    { categoryId: 'cat-objects', word: 'Liniaal',      hintEasy: 'Meten',      hintMedium: 'Recht',        hintHard: 'Centimeter' },
    { categoryId: 'cat-objects', word: 'Globus',       hintEasy: 'Aarde',      hintMedium: 'Landen',       hintHard: 'Ronddraaien' },
    { categoryId: 'cat-objects', word: 'Puzzel',       hintEasy: 'Stukjes',    hintMedium: 'Geduld',       hintHard: 'Compleet' },
    { categoryId: 'cat-objects', word: 'Dobbelstenen', hintEasy: 'Gooien',     hintMedium: 'Kansen',       hintHard: 'Geluk' },
    { categoryId: 'cat-objects', word: 'Speelkaarten', hintEasy: 'Spelen',     hintMedium: 'Azen',         hintHard: 'Poker' },
    { categoryId: 'cat-objects', word: 'Schaakstuk',   hintEasy: 'Schaken',    hintMedium: 'Bord',         hintHard: 'Strategie' },
    { categoryId: 'cat-objects', word: 'Verrekijker',  hintEasy: 'Kijken',     hintMedium: 'Afstand',      hintHard: 'Vergroten' },
    { categoryId: 'cat-objects', word: 'Vlag',         hintEasy: 'Mast',       hintMedium: 'Land',         hintHard: 'Trots' },
    { categoryId: 'cat-objects', word: 'Handschoen',   hintEasy: 'Hand',       hintMedium: 'Warm',         hintHard: 'Bescherming' },
    { categoryId: 'cat-objects', word: 'Riem',         hintEasy: 'Broek',      hintMedium: 'Leer',         hintHard: 'Gespe' },
    { categoryId: 'cat-objects', word: 'Paraplu',      hintEasy: 'Nat',        hintMedium: 'Weer',         hintHard: 'Beschutting' },
    { categoryId: 'cat-objects', word: 'Zonnebril',    hintEasy: 'Zon',        hintMedium: 'Zomer',        hintHard: 'Stijl' },
    { categoryId: 'cat-objects', word: 'Portemonnaie', hintEasy: 'Geld',       hintMedium: 'Leer',         hintHard: 'Kwijt' },
    { categoryId: 'cat-objects', word: 'Schoenlepel',  hintEasy: 'Schoen',     hintMedium: 'Aantrekken',   hintHard: 'Hak' },
    { categoryId: 'cat-objects', word: 'Kurketrekker', hintEasy: 'Wijn',       hintMedium: 'Draaien',      hintHard: 'Fles' },
    { categoryId: 'cat-objects', word: 'Bestek',       hintEasy: 'Eten',       hintMedium: 'Lepel',        hintHard: 'Zilver' },
    { categoryId: 'cat-objects', word: 'Wasmand',      hintEasy: 'Was',        hintMedium: 'Kleding',      hintHard: 'Wassen' },
    { categoryId: 'cat-objects', word: 'Zeepbel',      hintEasy: 'Zeep',       hintMedium: 'Lucht',        hintHard: 'Kwetsbaar' },

    // ─── BEROEPEN (50) ──────────────────────────────────────────
    { categoryId: 'cat-jobs', word: 'Dokter',       hintEasy: 'Ziekenhuis',  hintMedium: 'Gezondheid',   hintHard: 'Diagnose' },
    { categoryId: 'cat-jobs', word: 'Leraar',       hintEasy: 'School',      hintMedium: 'Klas',         hintHard: 'Kennis' },
    { categoryId: 'cat-jobs', word: 'Politieagent', hintEasy: 'Uniform',     hintMedium: 'Orde',         hintHard: 'Wet' },
    { categoryId: 'cat-jobs', word: 'Brandweerman', hintEasy: 'Brand',       hintMedium: 'Slang',        hintHard: 'Moed' },
    { categoryId: 'cat-jobs', word: 'Bakker',       hintEasy: 'Brood',       hintMedium: 'Oven',         hintHard: 'Vroeg' },
    { categoryId: 'cat-jobs', word: 'Piloot',       hintEasy: 'Vliegtuig',   hintMedium: 'Cockpit',      hintHard: 'Wolken' },
    { categoryId: 'cat-jobs', word: 'Kapper',       hintEasy: 'Haar',        hintMedium: 'Schaar',       hintHard: 'Stijl' },
    { categoryId: 'cat-jobs', word: 'Kok',          hintEasy: 'Koken',       hintMedium: 'Keuken',       hintHard: 'Recept' },
    { categoryId: 'cat-jobs', word: 'Tandarts',     hintEasy: 'Tanden',      hintMedium: 'Boor',         hintHard: 'Pijn' },
    { categoryId: 'cat-jobs', word: 'Architect',    hintEasy: 'Gebouwen',    hintMedium: 'Ontwerp',      hintHard: 'Constructie' },
    { categoryId: 'cat-jobs', word: 'Verpleegster', hintEasy: 'Zorg',        hintMedium: 'Ziekenhuis',   hintHard: 'Bescherming' },
    { categoryId: 'cat-jobs', word: 'Rechter',      hintEasy: 'Rechtbank',   hintMedium: 'Recht',        hintHard: 'Vonnis' },
    { categoryId: 'cat-jobs', word: 'Advocaat',     hintEasy: 'Rechtbank',   hintMedium: 'Verdedigen',   hintHard: 'Wet' },
    { categoryId: 'cat-jobs', word: 'Journalist',   hintEasy: 'Nieuws',      hintMedium: 'Schrijven',    hintHard: 'Waarheidsvinder' },
    { categoryId: 'cat-jobs', word: 'Fotograaf',    hintEasy: 'Camera',      hintMedium: 'Licht',        hintHard: 'Moment' },
    { categoryId: 'cat-jobs', word: 'Schilder',     hintEasy: 'Kwast',       hintMedium: 'Verf',         hintHard: 'Kunst' },
    { categoryId: 'cat-jobs', word: 'Beeldhouwer',  hintEasy: 'Beeld',       hintMedium: 'Steen',        hintHard: 'Vorm' },
    { categoryId: 'cat-jobs', word: 'Musicus',      hintEasy: 'Noten',       hintMedium: 'Concert',      hintHard: 'Harmonie' },
    { categoryId: 'cat-jobs', word: 'Acteur',       hintEasy: 'Toneel',      hintMedium: 'Rol',          hintHard: 'Masker' },
    { categoryId: 'cat-jobs', word: 'Schrijver',    hintEasy: 'Boek',        hintMedium: 'Woorden',      hintHard: 'Verhaal' },
    { categoryId: 'cat-jobs', word: 'Wetenschapper',hintEasy: 'Lab',         hintMedium: 'Experiment',   hintHard: 'Ontdekking' },
    { categoryId: 'cat-jobs', word: 'Astronaut',    hintEasy: 'Ruimte',      hintMedium: 'Raket',        hintHard: 'Zwaartekracht' },
    { categoryId: 'cat-jobs', word: 'Dierenarts',   hintEasy: 'Dieren',      hintMedium: 'Zorg',         hintHard: 'Spuit' },
    { categoryId: 'cat-jobs', word: 'Tuinman',      hintEasy: 'Tuin',        hintMedium: 'Planten',      hintHard: 'Schep' },
    { categoryId: 'cat-jobs', word: 'Loodgieter',   hintEasy: 'Buizen',      hintMedium: 'Water',        hintHard: 'Lek' },
    { categoryId: 'cat-jobs', word: 'Elektricien',  hintEasy: 'Stroom',      hintMedium: 'Kabel',        hintHard: 'Spanning' },
    { categoryId: 'cat-jobs', word: 'Timmerman',    hintEasy: 'Hout',        hintMedium: 'Hamer',        hintHard: 'Spijker' },
    { categoryId: 'cat-jobs', word: 'Boer',         hintEasy: 'Akker',       hintMedium: 'Oogst',        hintHard: 'Seizoen' },
    { categoryId: 'cat-jobs', word: 'Visser',       hintEasy: 'Hengel',      hintMedium: 'Zee',          hintHard: 'Geduld' },
    { categoryId: 'cat-jobs', word: 'Postbode',     hintEasy: 'Brieven',     hintMedium: 'Fiets',        hintHard: 'Bezorging' },
    { categoryId: 'cat-jobs', word: 'Vertegenwoordiger', hintEasy: 'Verkopen', hintMedium: 'Klant',      hintHard: 'Commissie' },
    { categoryId: 'cat-jobs', word: 'Reisagent',    hintEasy: 'Vakantie',    hintMedium: 'Vlucht',       hintHard: 'Bestemming' },
    { categoryId: 'cat-jobs', word: 'Bibliotheekmedewerker', hintEasy: 'Boeken', hintMedium: 'Stilte', hintHard: 'Catalogus' },
    { categoryId: 'cat-jobs', word: 'Monteur',      hintEasy: 'Auto',        hintMedium: 'Motor',        hintHard: 'Gereedschap' },
    { categoryId: 'cat-jobs', word: 'Makelaar',     hintEasy: 'Huis',        hintMedium: 'Verkopen',     hintHard: 'Commissie' },
    { categoryId: 'cat-jobs', word: 'Accountant',   hintEasy: 'Geld',        hintMedium: 'Belasting',    hintHard: 'Balans' },
    { categoryId: 'cat-jobs', word: 'Psycholoog',   hintEasy: 'Gedrag',      hintMedium: 'Therapie',     hintHard: 'Onderbewustzijn' },
    { categoryId: 'cat-jobs', word: 'Diëtist',      hintEasy: 'Eten',        hintMedium: 'Gezond',       hintHard: 'Calorieën' },
    { categoryId: 'cat-jobs', word: 'Ingenieur',    hintEasy: 'Bouwen',      hintMedium: 'Ontwerp',      hintHard: 'Berekening' },
    { categoryId: 'cat-jobs', word: 'Programmeur',  hintEasy: 'Computer',    hintMedium: 'Code',         hintHard: 'Bug' },
    { categoryId: 'cat-jobs', word: 'Dirigent',     hintEasy: 'Orkest',      hintMedium: 'Stokje',       hintHard: 'Maat' },
    { categoryId: 'cat-jobs', word: 'Bibliotheekmedewerker2', hintEasy: 'Boeken', hintMedium: 'Uitlenen', hintHard: 'Stilte' },
    { categoryId: 'cat-jobs', word: 'Kassamedewerkster', hintEasy: 'Betalen', hintMedium: 'Supermarkt',  hintHard: 'Scan' },
    { categoryId: 'cat-jobs', word: 'Beveiliger',   hintEasy: 'Bewaken',     hintMedium: 'Uniform',      hintHard: 'Camera' },
    { categoryId: 'cat-jobs', word: 'Choreograaf',  hintEasy: 'Dans',        hintMedium: 'Beweging',     hintHard: 'Ritme' },
    { categoryId: 'cat-jobs', word: 'Dj',           hintEasy: 'Muziek',      hintMedium: 'Platen',       hintHard: 'Feest' },
    { categoryId: 'cat-jobs', word: 'Straatveger',  hintEasy: 'Schoon',      hintMedium: 'Bezem',        hintHard: 'Vroeg' },
    { categoryId: 'cat-jobs', word: 'Taxichauffeur', hintEasy: 'Rijden',     hintMedium: 'Auto',         hintHard: 'Meter' },
    { categoryId: 'cat-jobs', word: 'Ober',         hintEasy: 'Restaurant',  hintMedium: 'Bestelling',   hintHard: 'Fooi' },
    { categoryId: 'cat-jobs', word: 'Kapster',      hintEasy: 'Haar',        hintMedium: 'Salon',        hintHard: 'Verf' },

    // ─── MUZIEK (45) ────────────────────────────────────────────
    { categoryId: 'cat-music', word: 'Piano',        hintEasy: 'Toetsen',     hintMedium: 'Klassiek',     hintHard: 'Ivoor' },
    { categoryId: 'cat-music', word: 'Gitaar',       hintEasy: 'Snaren',      hintMedium: 'Rock',         hintHard: 'Plectrum' },
    { categoryId: 'cat-music', word: 'Trommel',      hintEasy: 'Slaan',       hintMedium: 'Ritme',        hintHard: 'Sticks' },
    { categoryId: 'cat-music', word: 'Viool',        hintEasy: 'Strijken',    hintMedium: 'Orkest',       hintHard: 'Paardenhaar' },
    { categoryId: 'cat-music', word: 'Trompet',      hintEasy: 'Blazen',      hintMedium: 'Jazz',         hintHard: 'Ventiel' },
    { categoryId: 'cat-music', word: 'Saxofoon',     hintEasy: 'Jazz',        hintMedium: 'Blaas',        hintHard: 'Belg' },
    { categoryId: 'cat-music', word: 'Fluit',        hintEasy: 'Blazen',      hintMedium: 'Hout',         hintHard: 'Gaten' },
    { categoryId: 'cat-music', word: 'Harp',         hintEasy: 'Snaren',      hintMedium: 'Engel',        hintHard: 'Hemel' },
    { categoryId: 'cat-music', word: 'Accordeon',    hintEasy: 'Uitrekken',   hintMedium: 'Folk',         hintHard: 'Knopjes' },
    { categoryId: 'cat-music', word: 'Cello',        hintEasy: 'Strijken',    hintMedium: 'Diep',         hintHard: 'Resonans' },
    { categoryId: 'cat-music', word: 'Basgitaar',    hintEasy: 'Laag',        hintMedium: 'Band',         hintHard: 'Bodem' },
    { categoryId: 'cat-music', word: 'Keyboard',     hintEasy: 'Toetsen',     hintMedium: 'Elektronisch', hintHard: 'Preset' },
    { categoryId: 'cat-music', word: 'Doedelzak',    hintEasy: 'Schotland',   hintMedium: 'Blaas',        hintHard: 'Zak' },
    { categoryId: 'cat-music', word: 'Xylofoon',     hintEasy: 'Tikken',      hintMedium: 'Kleuren',      hintHard: 'Hout' },
    { categoryId: 'cat-music', word: 'Tuba',         hintEasy: 'Groot',       hintMedium: 'Laag',         hintHard: 'Koper' },
    { categoryId: 'cat-music', word: 'Pop',          hintEasy: 'Hitlijst',    hintMedium: 'Radio',        hintHard: 'Massa' },
    { categoryId: 'cat-music', word: 'Rock',         hintEasy: 'Gitaar',      hintMedium: 'Luid',         hintHard: 'Rebel' },
    { categoryId: 'cat-music', word: 'Jazz',         hintEasy: 'Improvisatie',hintMedium: 'Amerika',      hintHard: 'Vrijheid' },
    { categoryId: 'cat-music', word: 'Klassiek',     hintEasy: 'Orkest',      hintMedium: 'Mozart',       hintHard: 'Oud' },
    { categoryId: 'cat-music', word: 'Hiphop',       hintEasy: 'Rappen',      hintMedium: 'Beats',        hintHard: 'Straat' },
    { categoryId: 'cat-music', word: 'Reggae',       hintEasy: 'Jamaica',     hintMedium: 'Rastafari',    hintHard: 'Slow' },
    { categoryId: 'cat-music', word: 'Blues',        hintEasy: 'Droef',       hintMedium: 'Amerika',      hintHard: 'Mississippi' },
    { categoryId: 'cat-music', word: 'Opera',        hintEasy: 'Zingen',      hintMedium: 'Theater',      hintHard: 'Aria' },
    { categoryId: 'cat-music', word: 'Musical',      hintEasy: 'Toneel',      hintMedium: 'Dansen',       hintHard: 'Broadway' },
    { categoryId: 'cat-music', word: 'Lied',         hintEasy: 'Zingen',      hintMedium: 'Tekst',        hintHard: 'Refrein' },
    { categoryId: 'cat-music', word: 'Concert',      hintEasy: 'Optreden',    hintMedium: 'Podium',       hintHard: 'Applaus' },
    { categoryId: 'cat-music', word: 'Album',        hintEasy: 'Muziek',      hintMedium: 'Nummers',      hintHard: 'Collectie' },
    { categoryId: 'cat-music', word: 'Microfoon',    hintEasy: 'Zingen',      hintMedium: 'Geluid',       hintHard: 'Versterking' },
    { categoryId: 'cat-music', word: 'Platenspeler', hintEasy: 'Vinyl',       hintMedium: 'Naald',        hintHard: 'Nostalgie' },
    { categoryId: 'cat-music', word: 'Koptelefoon',  hintEasy: 'Luisteren',   hintMedium: 'Oren',         hintHard: 'Isolatie' },
    { categoryId: 'cat-music', word: 'Speaker',      hintEasy: 'Geluid',      hintMedium: 'Volume',       hintHard: 'Trillen' },
    { categoryId: 'cat-music', word: 'Muzieknoot',   hintEasy: 'Noot',        hintMedium: 'Bladmuziek',   hintHard: 'Frequentie' },
    { categoryId: 'cat-music', word: 'Ritme',        hintEasy: 'Tikken',      hintMedium: 'Slaan',        hintHard: 'Pols' },
    { categoryId: 'cat-music', word: 'Harmonie',     hintEasy: 'Samen',       hintMedium: 'Klanken',      hintHard: 'Balans' },
    { categoryId: 'cat-music', word: 'Melodie',      hintEasy: 'Zingen',      hintMedium: 'Noten',        hintHard: 'Gevoel' },
    { categoryId: 'cat-music', word: 'Festival',     hintEasy: 'Muziek',      hintMedium: 'Buitenlucht',  hintHard: 'Tent' },
    { categoryId: 'cat-music', word: 'Zanger',       hintEasy: 'Stem',        hintMedium: 'Podium',       hintHard: 'Microfoon' },
    { categoryId: 'cat-music', word: 'Orkest',       hintEasy: 'Instrumenten',hintMedium: 'Dirigent',     hintHard: 'Symfonie' },
    { categoryId: 'cat-music', word: 'Koor',         hintEasy: 'Groep',       hintMedium: 'Zingen',       hintHard: 'Stem' },
    { categoryId: 'cat-music', word: 'Fanfare',      hintEasy: 'Mars',        hintMedium: 'Dorp',         hintHard: 'Koninginnedag' },
    { categoryId: 'cat-music', word: 'Elektronisch', hintEasy: 'Synthesizer', hintMedium: 'Computer',     hintHard: 'Digitaal' },
    { categoryId: 'cat-music', word: 'Partituur',    hintEasy: 'Noten',       hintMedium: 'Bladmuziek',   hintHard: 'Componist' },
    { categoryId: 'cat-music', word: 'Karaoke',      hintEasy: 'Zingen',      hintMedium: 'Tekst',        hintHard: 'Japan' },
    { categoryId: 'cat-music', word: 'Klokkenspel',  hintEasy: 'Klokkentoren',hintMedium: 'Melodie',     hintHard: 'Carillon' },
    { categoryId: 'cat-music', word: 'Tamboerijn',   hintEasy: 'Schudden',    hintMedium: 'Ritme',        hintHard: 'Velletje' },

    // ─── NATUUR (45) ────────────────────────────────────────────
    { categoryId: 'cat-nature', word: 'Vulkaan',     hintEasy: 'Lava',        hintMedium: 'Berg',         hintHard: 'Magma' },
    { categoryId: 'cat-nature', word: 'Waterval',    hintEasy: 'Water',       hintMedium: 'Stroom',       hintHard: 'Donder' },
    { categoryId: 'cat-nature', word: 'Regenboog',   hintEasy: 'Regen',       hintMedium: 'Kleuren',      hintHard: 'Lichtbreking' },
    { categoryId: 'cat-nature', word: 'Woestijn',    hintEasy: 'Zand',        hintMedium: 'Droog',        hintHard: 'Oase' },
    { categoryId: 'cat-nature', word: 'Jungle',      hintEasy: 'Groen',       hintMedium: 'Regen',        hintHard: 'Wild' },
    { categoryId: 'cat-nature', word: 'Gletsjers',   hintEasy: 'Ijs',         hintMedium: 'Bergen',       hintHard: 'Smelten' },
    { categoryId: 'cat-nature', word: 'Bliksem',     hintEasy: 'Donder',      hintMedium: 'Storm',        hintHard: 'Energie' },
    { categoryId: 'cat-nature', word: 'Sneeuw',      hintEasy: 'Wit',         hintMedium: 'Koud',         hintHard: 'Kristal' },
    { categoryId: 'cat-nature', word: 'Tornado',     hintEasy: 'Wind',        hintMedium: 'Wervelend',    hintHard: 'Kansas' },
    { categoryId: 'cat-nature', word: 'Tsunami',     hintEasy: 'Golf',        hintMedium: 'Oceaan',       hintHard: 'Ramp' },
    { categoryId: 'cat-nature', word: 'Aardbeving',  hintEasy: 'Schudden',    hintMedium: 'Grond',        hintHard: 'Platen' },
    { categoryId: 'cat-nature', word: 'Maan',        hintEasy: 'Nacht',       hintMedium: 'Licht',        hintHard: 'Getijden' },
    { categoryId: 'cat-nature', word: 'Zon',         hintEasy: 'Warm',        hintMedium: 'Energie',      hintHard: 'Kern' },
    { categoryId: 'cat-nature', word: 'Sterren',     hintEasy: 'Nacht',       hintMedium: 'Ruimte',       hintHard: 'Melkweg' },
    { categoryId: 'cat-nature', word: 'Oceaan',      hintEasy: 'Zee',         hintMedium: 'Diepte',       hintHard: 'Blauw' },
    { categoryId: 'cat-nature', word: 'Meer',        hintEasy: 'Water',       hintMedium: 'Vissen',       hintHard: 'Stilte' },
    { categoryId: 'cat-nature', word: 'Rivier',      hintEasy: 'Stromen',     hintMedium: 'Water',        hintHard: 'Bron' },
    { categoryId: 'cat-nature', word: 'Berg',        hintEasy: 'Hoog',        hintMedium: 'Klimmen',      hintHard: 'Top' },
    { categoryId: 'cat-nature', word: 'Dal',         hintEasy: 'Laag',        hintMedium: 'Groen',        hintHard: 'Beschutting' },
    { categoryId: 'cat-nature', word: 'Bos',         hintEasy: 'Bomen',       hintMedium: 'Schaduw',      hintHard: 'Zuurstof' },
    { categoryId: 'cat-nature', word: 'Weiland',     hintEasy: 'Gras',        hintMedium: 'Koeien',       hintHard: 'Weide' },
    { categoryId: 'cat-nature', word: 'Strand',      hintEasy: 'Zand',        hintMedium: 'Zee',          hintHard: 'Zomer' },
    { categoryId: 'cat-nature', word: 'Rots',        hintEasy: 'Steen',       hintMedium: 'Hard',         hintHard: 'Oud' },
    { categoryId: 'cat-nature', word: 'Grot',        hintEasy: 'Donker',      hintMedium: 'Steen',        hintHard: 'Echo' },
    { categoryId: 'cat-nature', word: 'Fjord',       hintEasy: 'Noorwegen',   hintMedium: 'Water',        hintHard: 'Ijs' },
    { categoryId: 'cat-nature', word: 'Savanne',     hintEasy: 'Gras',        hintMedium: 'Afrika',       hintHard: 'Droog' },
    { categoryId: 'cat-nature', word: 'Koraalrif',   hintEasy: 'Koraal',      hintMedium: 'Zee',          hintHard: 'Kleur' },
    { categoryId: 'cat-nature', word: 'Moeras',      hintEasy: 'Nat',         hintMedium: 'Kikkers',      hintHard: 'Mist' },
    { categoryId: 'cat-nature', word: 'Tundra',      hintEasy: 'Ijs',         hintMedium: 'Koud',         hintHard: 'Permafrost' },
    { categoryId: 'cat-nature', word: 'Regenwoud',   hintEasy: 'Regen',       hintMedium: 'Amazone',      hintHard: 'Longenen' },
    { categoryId: 'cat-nature', word: 'Eiland',      hintEasy: 'Zee',         hintMedium: 'Afgezonderd',  hintHard: 'Paradijs' },
    { categoryId: 'cat-nature', word: 'Mist',        hintEasy: 'Grijs',       hintMedium: 'Nat',          hintHard: 'Zicht' },
    { categoryId: 'cat-nature', word: 'Aurora',      hintEasy: 'Licht',       hintMedium: 'Noorwegen',    hintHard: 'Magneet' },
    { categoryId: 'cat-nature', word: 'Komeet',      hintEasy: 'Staart',      hintMedium: 'Ruimte',       hintHard: 'Ijs' },
    { categoryId: 'cat-nature', word: 'Meteoriet',   hintEasy: 'Steen',       hintMedium: 'Ruimte',       hintHard: 'Krater' },
    { categoryId: 'cat-nature', word: 'Geiser',      hintEasy: 'Stoom',       hintMedium: 'Heet',         hintHard: 'IJsland' },
    { categoryId: 'cat-nature', word: 'Zonsopgang',  hintEasy: 'Ochtend',     hintMedium: 'Oranje',       hintHard: 'Horizon' },
    { categoryId: 'cat-nature', word: 'Zonsondergang',hintEasy: 'Avond',      hintMedium: 'Rood',         hintHard: 'Stilte' },
    { categoryId: 'cat-nature', word: 'Stormbui',    hintEasy: 'Regen',       hintMedium: 'Wind',         hintHard: 'Kracht' },
    { categoryId: 'cat-nature', word: 'Hitte',       hintEasy: 'Warm',        hintMedium: 'Zon',          hintHard: 'Dorst' },
    { categoryId: 'cat-nature', word: 'Hagel',       hintEasy: 'Ijs',         hintMedium: 'Neerslag',     hintHard: 'Ruit' },
    { categoryId: 'cat-nature', word: 'Vloed',       hintEasy: 'Water',       hintMedium: 'Rivier',       hintHard: 'Ramp' },
    { categoryId: 'cat-nature', word: 'Droogte',     hintEasy: 'Droog',       hintMedium: 'Afrika',       hintHard: 'Honger' },
    { categoryId: 'cat-nature', word: 'Ecosysteem',  hintEasy: 'Natuur',      hintMedium: 'Keten',        hintHard: 'Balans' },
    { categoryId: 'cat-nature', word: 'Luchtspiegeling', hintEasy: 'Woestijn', hintMedium: 'Water',      hintHard: 'Illlusie' },
  ]

  // Upsert all words
  const allWords = [...words, ...allExtraWords]
  let count = 0
  for (const w of allWords) {
    const id = `${w.categoryId}-${w.word.toLowerCase().replace(/[^a-z0-9]/g, '-')}`
    await prisma.word.upsert({
      where: { id },
      update: {},
      create: { id, ...w },
    })
    count++
  }

  console.log(`✅ Created/updated ${count} words across 8 categories`)
  console.log('🎉 Seeding complete!')
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
