import type { AvatarPreset } from '@imposter-game/shared'

// Each avatar has a unique gradient pair [from, to] for their card background
export const AVATAR_PRESETS: (AvatarPreset & { emoji: string; colors: [string, string] })[] = [
  {
    id: 'fox',
    name: 'Vos',
    emoji: '🦊',
    colors: ['#F97316', '#DC2626'],
    imageNotViewed: '/avatars/vos-open.png',
    imageViewed: '/avatars/vos-gesloten.png',
  },
  {
    id: 'panda',
    name: 'Panda',
    emoji: '🐼',
    colors: ['#374151', '#1E293B'],
    imageNotViewed: '/avatars/panda-sleeping.svg',
    imageViewed: '/avatars/panda-awake.svg',
  },
  {
    id: 'lion',
    name: 'Leeuw',
    emoji: '🦁',
    colors: ['#D97706', '#B45309'],
    imageNotViewed: '/avatars/leeuw-open.png',
    imageViewed: '/avatars/leeuw-gesloten.png',
  },
  {
    id: 'cat',
    name: 'Kat',
    emoji: '🐱',
    colors: ['#9333EA', '#DB2777'],
    imageNotViewed: '/avatars/cat-sleeping.svg',
    imageViewed: '/avatars/cat-awake.svg',
  },
  {
    id: 'dog',
    name: 'Hond',
    emoji: '🐶',
    colors: ['#0284C7', '#1D4ED8'],
    imageNotViewed: '/avatars/dog-sleeping.svg',
    imageViewed: '/avatars/dog-awake.svg',
  },
  {
    id: 'owl',
    name: 'Uil',
    emoji: '🦉',
    colors: ['#0D9488', '#059669'],
    imageNotViewed: '/avatars/uil-links.png',
    imageViewed: '/avatars/uil-rechts.png',
  },
  {
    id: 'rabbit',
    name: 'Konijn',
    emoji: '🐰',
    colors: ['#EC4899', '#E11D48'],
    imageNotViewed: '/avatars/konijn-links.png',
    imageViewed: '/avatars/konijn-rechts.png',
  },
  {
    id: 'wizard',
    name: 'Tovenaar',
    emoji: '🧙',
    colors: ['#6D28D9', '#4338CA'],
    imageNotViewed: '/avatars/tovenaar-links.png',
    imageViewed: '/avatars/tovenaar-rechts.png',
  },
  {
    id: 'princess',
    name: 'Prinses',
    emoji: '👸',
    colors: ['#BE185D', '#7C3AED'],
    imageNotViewed: '/avatars/princess-sleeping.svg',
    imageViewed: '/avatars/princess-awake.svg',
  },
  {
    id: 'ghost',
    name: 'Spookje',
    emoji: '👻',
    colors: ['#4B5563', '#6D28D9'],
    imageNotViewed: '/avatars/ghost-sleeping.svg',
    imageViewed: '/avatars/ghost-awake.svg',
  },
  {
    id: 'superhero',
    name: 'Superheld',
    emoji: '🦸',
    colors: ['#DC2626', '#D97706'],
    imageNotViewed: '/avatars/superhero-sleeping.svg',
    imageViewed: '/avatars/superhero-awake.svg',
  },
  {
    id: 'cowboys',
    name: 'Cowboys',
    emoji: '🤠',
    colors: ['#92400E', '#78350F'],
    imageNotViewed: '/avatars/cowboys-open.png',
    imageViewed: '/avatars/cowboys-gesloten.png',
  },
  {
    id: 'draakjes',
    name: 'Draakjes',
    emoji: '🐉',
    colors: ['#065F46', '#4C1D95'],
    imageNotViewed: '/avatars/draakjes-open.png',
    imageViewed: '/avatars/draakjes-gesloten.png',
  },
  {
    id: 'koningen',
    name: 'Koningen',
    emoji: '👑',
    colors: ['#78350F', '#6D28D9'],
    imageNotViewed: '/avatars/koningen-open.png',
    imageViewed: '/avatars/koningen-gesloten.png',
  },
  {
    id: 'imposter1',
    name: 'Norah',
    emoji: '😈',
    colors: ['#1E293B', '#DC2626'],
    imageNotViewed: '/avatars/imposter1.png',
    imageViewed: '/avatars/imposter1-gesloten.png',
  },
  {
    id: 'imposter2',
    name: 'Imposter',
    emoji: '😈',
    colors: ['#DC2626', '#1E293B'],
    imageNotViewed: '/avatars/imposter2.png',
    imageViewed: '/avatars/norah.png',
  },
  {
    id: 'slang',
    name: 'Slang',
    emoji: '🐍',
    colors: ['#065F46', '#14532D'],
    imageNotViewed: '/avatars/slang-gesloten.png',
    imageViewed: '/avatars/slang-open.png',
  },
  {
    id: 'robot',
    name: 'Robot',
    emoji: '🤖',
    colors: ['#0369A1', '#0E7490'],
    imageNotViewed: '/avatars/robot-gesloten.png',
    imageViewed: '/avatars/robot-open.png',
  },
  {
    id: 'ridder',
    name: 'Ridder',
    emoji: '⚔️',
    colors: ['#374151', '#6D28D9'],
    imageNotViewed: '/avatars/ridder-gesloten.png',
    imageViewed: '/avatars/ridder-open.png',
  },
]

export function getAvatarById(id: string) {
  return AVATAR_PRESETS.find((avatar) => avatar.id === id)
}

export function getRandomAvatar() {
  return AVATAR_PRESETS[Math.floor(Math.random() * AVATAR_PRESETS.length)]
}
